### ISSUE TITLE
Race condition when associating BMH with M3M

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/cluster-api-provider-metal3#1004]
**What steps did you take and what happened:**

There seems to be a race condition when we associate Metal3Machines with BareMetalHosts.
We recently saw an error in the CI where a BareMetalHost failed to provision after the remediation test where we mark one as unhealthy.
After some debugging we found out that two of the Metal3Machines had selected the same BareMetalHost:

```console
$ kubectl get m3m -n metal3 -o jsonpath="{.items[*].metadata.annotations.metal3\.io/BareMetalHost}"
metal3/node-1 metal3/node-2 metal3/node-3 metal3/node-3
```

CAPM3 logs showed some errors because of this condition:

```
I0529 11:35:59.723046       1 metal3machine_manager.go:1111] controllers/Metal3Machine/Metal3Machine-controller "msg"="Deleting nodeReuseLabelName from host, if any" "cluster"="test1" "machine"="test1-55
b88586c9xhzbds-9r565" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-workers-f7b82"}                                                                                        
E0529 11:35:59.759720       1 controller.go:329]  "msg"="Reconciler error" "error"="failed to update BareMetalHost: BareMetalHost.metal3.io \"node-3\" is invalid: [metadata.ownerReferences: Invalid value
: []v1.OwnerReference{v1.OwnerReference{APIVersion:\"infrastructure.cluster.x-k8s.io/v1beta1\", Kind:\"Metal3Machine\", Name:\"test1-workers-kw96b\", UID:\"3ddf1600-fa1e-435d-a05a-3260e0bf4b5d\", Control
ler:(*bool)(0xc0256c8a38), BlockOwnerDeletion:(*bool)(nil)}, v1.OwnerReference{APIVersion:\"infrastructure.cluster.x-k8s.io/v1beta1\", Kind:\"Metal3Machine\", Name:\"test1-workers-f7b82\", UID:\"b3a2a2af
-fab2-4d7d-9f8c-4ace096082c8\", Controller:(*bool)(0xc0256c8a3a), BlockOwnerDeletion:(*bool)(nil)}}: Only one reference can have Controller set to true. Found \"true\" in references for Metal3Machine/tes
t1-workers-kw96b and Metal3Machine/test1-workers-f7b82, metadata.ownerReferences: Invalid value: []v1.OwnerReference{v1.OwnerReference{APIVersion:\"infrastructure.cluster.x-k8s.io/v1beta1\", Kind:\"Metal
3Machine\", Name:\"test1-workers-kw96b\", UID:\"3ddf1600-fa1e-435d-a05a-3260e0bf4b5d\", Controller:(*bool)(0xc0256c8a50), BlockOwnerDeletion:(*bool)(nil)}, v1.OwnerReference{APIVersion:\"infrastructure.c
luster.x-k8s.io/v1beta1\", Kind:\"Metal3Machine\", Name:\"test1-workers-f7b82\", UID:\"b3a2a2af-fab2-4d7d-9f8c-4ace096082c8\", Controller:(*bool)(0xc0256c8a52), BlockOwnerDeletion:(*bool)(nil)}}: Only on
e reference can have Controller set to true. Found \"true\" in references for Metal3Machine/test1-workers-kw96b and Metal3Machine/test1-workers-f7b82, metadata.ownerReferences: Invalid value: []v1.OwnerR
eference{v1.OwnerReference{APIVersion:\"infrastructure.cluster.x-k8s.io/v1beta1\", Kind:\"Metal3Machine\", Name:\"test1-workers-kw96b\", UID:\"3ddf1600-fa1e-435d-a05a-3260e0bf4b5d\", Controller:(*bool)(0
xc0256c8a68), BlockOwnerDeletion:(*bool)(nil)}, v1.OwnerReference{APIVersion:\"infrastructure.cluster.x-k8s.io/v1beta1\", Kind:\"Metal3Machine\", Name:\"test1-workers-f7b82\", UID:\"b3a2a2af-fab2-4d7d-9f
8c-4ace096082c8\", Controller:(*bool)(0xc0256c8a6a), BlockOwnerDeletion:(*bool)(nil)}}: Only one reference can have Controller set to true. Found \"true\" in references for Metal3Machine/test1-workers-kw
96b and Metal3Machine/test1-workers-f7b82]" "Metal3Machine"={"name":"test1-workers-f7b82","namespace":"metal3"} "controller"="metal3machine" "controllerGroup"="infrastructure.cluster.x-k8s.io" "controlle
rKind"="Metal3Machine" "name"="test1-workers-f7b82" "namespace"="metal3" "reconcileID"="bcdce999-994b-418f-8edc-aa70aff4e468"
```

Indeed, we could see earlier in the logs that two M3Ms were associated with the same BMH:

```
I0529 08:21:39.782222       1 metal3machine_manager.go:290] controllers/Metal3Machine/Metal3Machine-controller "msg"="Associating machine" "cluster"="test1" "machine"="test1-55b88586c9xhzbds-9r565" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-workers-f7b82"}
I0529 08:21:39.792830       1 metal3machine_manager.go:873] controllers/Metal3Machine/Metal3Machine-controller "msg"="Host matched hostSelector for Metal3Machine, adding it to availableHosts list" "cluster"="test1" "host"="node-3" "machine"="test1-55b88586c9xhzbds-9r565" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-workers-f7b82"}
I0529 08:21:39.788610       1 metal3machine_manager.go:290] controllers/Metal3Machine/Metal3Machine-controller "msg"="Associating machine" "cluster"="test1" "machine"="test1-55b88586c9xhzbds-hpht4" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-workers-kw96b"}
I0529 08:21:39.797960       1 metal3machine_manager.go:873] controllers/Metal3Machine/Metal3Machine-controller "msg"="Host matched hostSelector for Metal3Machine, adding it to availableHosts list" "cluster"="test1" "host"="node-3" "machine"="test1-55b88586c9xhzbds-hpht4" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-workers-kw96b"}
I0529 08:21:39.798009       1 metal3machine_manager.go:881] controllers/Metal3Machine/Metal3Machine-controller "msg"="Host count available with nodeReuseLabelName while choosing host for Metal3 machine" "cluster"="test1" "hostcount"=0 "machine"="test1-55b88586c9xhzbds-hpht4" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-workers-kw96b"}
I0529 08:21:39.798047       1 metal3machine_manager.go:882] controllers/Metal3Machine/Metal3Machine-controller "msg"="Host count available while choosing host for Metal3 machine" "cluster"="test1" "hostcount"=1 "machine"="test1-55b88586c9xhzbds-hpht4" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-workers-kw96b"}
I0529 08:21:39.798067       1 metal3machine_manager.go:918] controllers/Metal3Machine/Metal3Machine-controller "msg"="host(s) count available, choosing a random host" "availabeHostCount"=1 "cluster"="test1" "machine"="test1-55b88586c9xhzbds-hpht4" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-workers-kw96b"}
I0529 08:21:39.798349       1 metal3machine_manager.go:318] controllers/Metal3Machine/Metal3Machine-controller "msg"="Associating machine with host" "cluster"="test1" "host"="node-3" "machine"="test1-55b88586c9xhzbds-hpht4" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-workers-kw96b"}
I0529 08:21:39.798416       1 metal3machine_manager.go:1111] controllers/Metal3Machine/Metal3Machine-controller "msg"="Deleting nodeReuseLabelName from host, if any" "cluster"="test1" "machine"="test1-55b88586c9xhzbds-hpht4" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-workers-kw96b"}
I0529 08:21:39.799368       1 metal3machine_manager.go:881] controllers/Metal3Machine/Metal3Machine-controller "msg"="Host count available with nodeReuseLabelName while choosing host for Metal3 machine" "cluster"="test1" "hostcount"=0 "machine"="test1-55b88586c9xhzbds-9r565" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-workers-f7b82"}
I0529 08:21:39.799443       1 metal3machine_manager.go:882] controllers/Metal3Machine/Metal3Machine-controller "msg"="Host count available while choosing host for Metal3 machine" "cluster"="test1" "hostcount"=1 "machine"="test1-55b88586c9xhzbds-9r565" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-workers-f7b82"}
I0529 08:21:39.799544       1 metal3machine_manager.go:918] controllers/Metal3Machine/Metal3Machine-controller "msg"="host(s) count available, choosing a random host" "availabeHostCount"=1 "cluster"="test1" "machine"="test1-55b88586c9xhzbds-9r565" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-workers-f7b82"}
I0529 08:21:39.803207       1 metal3machine_manager.go:318] controllers/Metal3Machine/Metal3Machine-controller "msg"="Associating machine with host" "cluster"="test1" "host"="node-3" "machine"="test1-55b
88586c9xhzbds-9r565" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-workers-f7b82"}
I0529 08:21:39.803240       1 metal3machine_manager.go:1111] controllers/Metal3Machine/Metal3Machine-controller "msg"="Deleting nodeReuseLabelName from host, if any" "cluster"="test1" "machine"="test1-55b88586c9xhzbds-9r565" "metal3-cluster"="test1" "metal3-machine"={"Namespace":"metal3","Name":"test1-workers-f7b82"}
```

**What did you expect to happen:**

This error should not happen. CAPM3 should be able to handle it and ensure that two M3Ms don't select the same BMH.

**Anything else you would like to add:**

Before https://github.com/metal3-io/cluster-api-provider-metal3/pull/884 there was no concurrency, and so this issue would not have been possible.
I'm now wondering if we should revert, or set concurrency to 1 or try to do a proper fix directly.
Since the concurrency was part of v1.4.0, this issue is already in the release.
A simple mitigation is to set concurrency to 1.

**Environment:**

- Cluster-api version: -
- Cluster-api-provider-metal3 version: main/v1.4.0
- Environment (metal3-dev-env or other): -
- Kubernetes version: (use `kubectl version`): -

/kind bug

**Comment by ydp** [comment]
This issue is very easy to reproduce and affects cluster creation, can we make a new release that includes this fix? Thanks!

**Comment by tuminoid** [comment]
> This issue is very easy to reproduce and affects cluster creation, can we make a new release that includes this fix? Thanks!

We aim to cut a 1.4.1 release next week.

**Comment by lentzi90** [comment]
/reopen
We saw this today in CI here: https://jenkins.nordix.org/blue/organizations/jenkins/metal3_daily_main_e2e_feature_test_centos/detail/metal3_daily_main_e2e_feature_test_centos/144/pipeline

**Comment by lentzi90** [comment]
The issue is most likely due to caching. Here is what I have found:

1. We do not specify any specific client when creating the Manager, so defaults will be used. https://github.com/Nordix/cluster-api-provider-metal3/blob/5407f44da387b7cbbcc95910ecfba6209070cab1/main.go#L104-L118
2. The default is to use cache when reading but not when writing
   > 	// NewClient is the func that creates the client to be used by the manager.
   > // If not set this will create the default DelegatingClient that will
   > // use the cache for reads and the client for writes.
   > https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.14.5/pkg/manager#New
3. Locking is then not enough because the following call to the function could use outdated data (cache) to choose the host.
   In particular [this](https://github.com/Nordix/cluster-api-provider-metal3/blob/5407f44da387b7cbbcc95910ecfba6209070cab1/baremetal/metal3machine_manager.go#L864C21-L864C21) call to list the hosts could return data that shows a host not yet associated when in fact it already was associated.

**Comment by zaneb** [comment]
As noted [here](https://github.com/metal3-io/baremetal-operator/pull/2996#discussion_r2858101801), the problem is that #80 switched from calling `Update()`, which fails with a conflict error if the object has been modified since we read it, to `Patch()`, which happily overwrites whatever part of the object you want regardless of its current value. This completely discards the compare-and-swap functionality of the k8s API that is the whole purpose of having a consumerRef field.

So the sequence of events is:

- M3M _A_ claims a BMH by patching the consumerRef and owner references in `Associate()`. It annotates itself with that BMH.
- M3M _B_ claims the same BMH by patching the same fields, overwriting the values set by `A`. It also annotates itself with that same BMH.
- M3M _A_ in `Update()` reads the BMH as written by _B_ and attempts to patch it by adding its owner reference. Since the controller flag is set in both owner references, the patch is rejected with the error message shown in the log above.

The correct solution to the issue in #79 is to check that we are actually changing something before calling `Update()`, or to [filter the events](https://github.com/metal3-io/baremetal-operator/blob/release-0.12/internal/controller/metal3.io/baremetalhost_controller.go#L2331-L2334).

**Comment by zaneb** [comment]
I opened #3189.

For future reference, in a distributed system:

- The problem is **never** caching. Any problem that shows up because of a stale cache can also happen when there is no cache.
- The solution is never mutexes. Any problem caused by stale writes within a single process will also show up between different clients.
