### ISSUE TITLE
Looking for the right way to provide Static IPs for masters and workers. 

### ISSUE THREAD

**Issue by tssavita** [metal3-io/cluster-api-provider-metal3#107]
I was not sure in which category this fit and hence the blank template. 

Use case: I would like to have 1 master and 2 workers in my cluster. I want to create bond interfaces in the baremetalhosts and set static IPs for these workers. 

Your documentation here: https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/docs/getting-started.md is quite useful! 
However in my case I would probably need to provide separate env variables for separate workers, right(As the kubeadmconfigtemplate is going to look different for both the hosts)? Is it possible to get the cluster configuration for such a use case, through clusterctl? Or would I need to manually edit the output from clusterctl to include two kubeadmconfig and reference them in two separate machine CRs.

**Comment by maelk** [comment]
Hi! You can unfortunately use static IP address allocations and MachineDeployment / KubeadmControlPlane only if your hardware is homogeneous. i.e. the same configuration can be applied on both hosts. So if your hardware is exactly the same with the same interface order and connectivity, then you can use a machine deployment with a KubeadmConfigTemplate and Metal3DataTemplate for the two workers. If it is not the case, then you cannot use MachineDeployment.

However, you can still create individual machines and their static configuration, that is supported. so you might not need to do any changes in you KubeadmConfig if you use a Metal3DataTemplate or directly give the networkdata secret in your Metal3Machine.

Bonds are supported in Metal3DataTemplates and networkdata secrets (unfortunately still untested though).

**Comment by tssavita** [comment]
Got it. Will provide and test bond network interface information through Metal3DataTemplate and create separate machines which have same kubeadmconfig.
