### ISSUE TITLE
Can I use pools in different namespaces ？

### ISSUE THREAD

**Issue by huaqing1994** [metal3-io/cluster-api-provider-metal3#1071]
**User Story**

As a developer I would like to use an IPPool in other namespace in CAPM3 for Metal3Clusters in different namespaces can be associated with a common IPPool.

**Detailed Description**

I found that when filling `IPPool` in `Metal3DataTemplate`, you can only fill in `name`, not `namespace`.
The need to allow IPPools with different namespaces should be reasonable, like `corev1.SecretReference` and `corev1.ObjectReference`.
I don't know what the reason for this design is, if anyone knows, thanks for letting me know. And I hope this can be improved in the future.

Thank you all! :)

/kind feature

**Comment by Rozzii** [comment]
The feature you describe here @huaqing1994 makes sense, but as far as I know k8s operators could be configured to watch either 1 namespace or all namespaces thus the use-case you describe where the operator is able to selectively access resources in different namespaces might not be supported. But I am not an expert in this topic so I hope others from the community can add extra info here.

**Comment by mboukhalfa** [comment]
There might be also issue with `ownerReference`  since it can only point to resource in the same namespace or cluster-wide resource as already investigated here
https://github.com/metal3-io/cluster-api-provider-metal3/pull/795#issuecomment-1334987487
