### ISSUE TITLE
Not overwrite networkdata if it already exists in BMH

### ISSUE THREAD

**Issue by ydp** [metal3-io/cluster-api-provider-metal3#1091]
**User Story**

As a [developer/user/operator] I would like to management IP allocation outside of metal3, when BMH already has a network data specified, it should not be overwritten.

**Detailed Description**

I want to manage IP allocation by myself, currently the node IP is either allocated by metal3-ipam or using dhcp, but I don't want both, there is no way to achieve that as far as I know, I see BMH support specify networkData, but when I set it, [it will be overwritten by metal3machine controller](https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/baremetal/metal3machine_manager.go#L1081), could we add an option to avoid it? 

I only want to customize network data, the dataTemplate is still needed, so I cannot leave networkData empty, as the doc says `If the dataTemplate field is set but either the renderedData, metaData or networkData fields in the status are unset, then the Metal3Machine controller will wait until it can find the Metal3Data object and the rendered secrets. It will then populate those fields.`

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by Rozzii** [comment]
Have you tried not referencing networkData on the Machine/MachineTemplate level ? Does it overwrite the secret reference of the BMH even when you only specify networkData in the BMH and nowhere else ?

**Comment by Rozzii** [comment]
We have to investigate this but on the first glance this is a valid use-case, I am not sure when would this be implemented.
Would you be willing to implement this @ydp ?
/triage accepted

**Comment by ydp** [comment]
> We have to investigate this but on the first glance this is a valid use-case, I am not sure when would this be implemented. Would you be willing to implement this @ydp ? /triage accepted

Hi @Rozzii  Thanks for reply, I would love to implement, my use case is that I am doing an IPam completely outside of metal3, more specifically, I would like each machine get a fixed IP even before cluster provision, I personally not sure if this is a best practice in industry, but based on my understanding, since we are managing bare metal, it would be much more convenient if machine has a fixed IP. This is why I want to set the NetworkData in BMH instead of getting it from metal3machine. 

I have already implemented a way to do it here https://github.com/ydp/cluster-api-provider-metal3/commit/e29874c09253032c7d25c8fd17aceab3ac9b5a6c ,  but this might be too hacky? because I used naming to decide whether there is user specified network data. If you have any better idea, I would love to implement it.

BTW, at first, I also try to let the metal3machine controller not wait for network data, it can still continue even if network data empty, but this would change the current behavior.

**Comment by ydp** [comment]
I think I just found that the API docs is not accurate:
> If the dataTemplate field is set but either the renderedData, metaData or networkData fields in the status are unset, then the Metal3Machine controller will wait until it can find the Metal3Data object and the rendered secrets. It will then populate those fields.

Because then I tried again, that when the networkData field in dataTemplate is not set, metal3machine controller will not wait for it. 

If it's nil here https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/baremetal/metal3data_manager.go#L186 , https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/baremetal/metal3data_manager.go#L211 metal3Data will be considered ready, then it passes the check https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/baremetal/metal3machine_manager.go#L1587 , 

see my data:
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Data
metadata:
  creationTimestamp: "2023-07-19T18:18:50Z"
  finalizers:
  - metal3data.infrastructure.cluster.x-k8s.io
  generation: 2
  labels:
    cluster.x-k8s.io/cluster-name: test1
    cluster.x-k8s.io/control-plane: ""
    cluster.x-k8s.io/control-plane-name: test1
  name: test1-controlplane-template-0
  namespace: default
  ownerReferences:
  - apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    controller: true
    kind: Metal3DataTemplate
    name: test1-controlplane-template
    uid: d4668ea0-841b-4724-adbe-dd51587fee51
  - apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3DataClaim
    name: test1-controlplane-clvw9
    uid: 72deffbf-b884-4139-9ea3-f1c621f45bd8
  - apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3Machine
    name: test1-controlplane-clvw9
    uid: 6eff76fb-b928-4547-90d8-a297d0522684
  resourceVersion: "2375"
  uid: a9a0f9ce-29d4-4b54-bac6-b84ef06623f4
spec:
  claim:
    name: test1-controlplane-clvw9
    namespace: default
  metaData:
    name: test1-controlplane-clvw9-metadata
    namespace: default
  template:
    name: test1-controlplane-template
    namespace: default
status:
  ready: true
```
So, looks like my code is not needed, and I don't have to implement anything. Maybe we should change the doc a little?
