### ISSUE TITLE
IRONIC_USE_MARIADB option failed the dev-env test for release-1.2 and 1.3. 

### ISSUE THREAD

**Issue by smoshiur1237** [metal3-io/cluster-api-provider-metal3#1100]
**What steps did you take and what happened:**
We tried to use MariaDB with dev-env as a workaround to the database locking issue by SQLite. It worked perfectly with main and release-1.4 but failed to pass with release-1.2 and release-1.3.  We made changes in JJB, Project-infra, Metal3-dev-env and CAPM3. It seems that setting `IRONIC_USE_MARIADB` `true` adds `-m `option for older releases of CAPM3 and BMO, which is not a valid option.  Thus was failing in the deploy script.  If the variable set to `flase` that means not to use mariaDB, it works with all the releases of CAPM3 and BMO. 

After we get the fix for SQLite database fix from ironic, reverted all the changes related to the use of MariaDB.

**What did you expect to happen:**
It should work with all the CAPM3 releases.

**Anything else you would like to add:**
This needs a clear solution on how to use the variables which are not valid in release-1.3 and rlease-1.2

**Environment:**
- Environment (metal3-dev-env or other):

/kind bug

**Comment by kashifest** [comment]
is this still flaky @smoshiur1237

**Comment by smoshiur1237** [comment]
Yes, the configuration in dev-env need modification to enable mariiadb for release 1.2 and 1.3
