### ISSUE TITLE
[Flaky Test] Clusterctl e2e test is failing to create the target cluster

### ISSUE THREAD

**Issue by mboukhalfa** [metal3-io/cluster-api-provider-metal3#1110]
### Which jobs are flaking?

Clusterctl upgrade from 1.3 and 1.4

### Which tests are flaking?

https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_from-release-1-3_main_e2e_clusterctl_upgrade_test_ubuntu/
https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_from-release-1-4_main_e2e_clusterctl_upgrade_test_ubuntu/69/

### Since when has it been flaking?

Jul 27, 2023, 1:44:01 AM

### Jenkins link

https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_from-release-1-4_main_e2e_clusterctl_upgrade_test_ubuntu/69/

### Reason for failure (if possible)

It is not clear from the logs seems the creation of the cluster hanging waiting for kcp to be running so It might be ironic is not available
```
INFO: Waiting for the cluster infrastructure to be provisioned
  STEP: Waiting for cluster to enter the provisioned phase @ 07/27/23 01:59:19.522
  INFO: Waiting for control plane to be initialized
  INFO: Waiting for the first control plane machine managed by clusterctl-upgrade-5ds2pm/clusterctl-upgrade-3yc317 to be provisioned
  STEP: Waiting for one control plane node to exist @ 07/27/23 01:59:19.551
  [FAILED] in [It] - /home/****/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.4.2/framework/controlplane_helpers.go:153 @ 07/27/23 02:29:19.553
  < Exit [It] Should create a management cluster and then upgrade all the providers @ 07/27/23 02:29:19.554 (30m26.087s)
  > Enter [AfterEach] When testing cluster upgrade from releases v1.3.3 > current [clusterctl-upgrade] @ 07/27/23 02:29:19.554
  STEP: Running PreCleanupManagementCluster steps against the management cluster @ 07/27/23 02:29:19.554
```

### Label(s) to be applied

/kind flake

**Comment by kashifest** [comment]
It has been in the CI once again in  https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_from-release-1-3_main_e2e_clusterctl_upgrade_test_ubuntu/68/

**Comment by mboukhalfa** [comment]
@Sunnatillo Do you know if this was fixed I did not see it on the ci this week at least

**Comment by Sunnatillo** [comment]
@mboukhalfa I did not see it as well. Lets wait for some time if this comes back, I will take a look.

**Comment by Rozzii** [comment]
I will let it get auto closed if nobody is seeing this (Just a reminder to myself)
