### ISSUE TITLE
Support for PXE only hosts

### ISSUE THREAD

**Issue by lieberlois** [metal3-io/cluster-api-provider-metal3#1174]
**User Story**

As a operator I would like to deploy k8s clusters using metal3 on machines with just PXE so that I can also support machine that only have PXE boot but no IPMI/LOM/etc.

**Detailed Description**

I have bare metal hosts laying around which I want to transform into K8s nodes. Using metal3, I want to deploy K8s. However, my hosts dont have an IPMI or BMC interface. The docs state that you need that however - but I'm not sure why, manually booting the PC should be enough.

**Anything else you would like to add:**

None

/kind feature

**Comment by dtantsur** [comment]
So, something along these lines? https://docs.openstack.org/ironic/latest/admin/agent-power.html

This could work, but you lose a lot of declared features: `online` field, deprovisioning, BIOS settings. I'm not sure how to handle that.

**Comment by Rozzii** [comment]
@lieberlois, to reiterate @dtantsur 's answer, Metal3 can only reliably support functionality that is already integrated into the Ironic end to end workflow. PXE is just the boot protocol, it does not provide anything related to life cycle management so you would need to develop custom stuff, e.g. additional deploy steps for IPA (the provisioning agent) and most probably a custom Ironic driver (something like "pxe-only") that implements Ironic interfaces like power, management and so on... I am not sure there is a general (enough) way to implement this PXE only workflow in a way that it would be useful for the community.   

In Metal3 the goal is to initiate a full e2e provisioning, cleaning, inspection, deprovisioning Ironic workflow by just adding a relatively small number of parameters to a manifest and applying the manifests. So basically you just say I want X workflow to provision and hit apply. So on the abstraction level of Metal3 we can't initiate only parts of a life-cycle management workflow.

If you just use Ironic you can mix together different interfaces and run certain life-cycle operations with this "customized" set of interfaces/functionality. (by interfaces i refer to Ironic's concept of "interface"  )

In any case I am not against the idea but this workflow would need standardized  full lifecycle management capable support in Ironic first before it could be supported in Metal3.
