### ISSUE TITLE
De-provisioning and immediately Provisioning a CP node not starting

### ISSUE THREAD

**Issue by Xenwar** [metal3-io/cluster-api-provider-metal3#122]
**What steps did you take and what happened:**

1. Provision a controlplane node, wait until it is provisioned.
2. Then run the following command
`./scripts/v1alphaX/deprovision_cluster.sh && ./scripts/v1alphaX/provision_cluster.sh && ./scripts/v1alphaX/provision_controlplane.sh`

The result is that a new kcp resource is saved to etcd, but no CP node is provisioned. 

**What did you expect to happen:**
The old CP node is de-provisioned and a new CP node is provisioned.

**Anything else you would like to add:**
Earlier, https://github.com/metal3-io/cluster-api-provider-metal3/issues/42 was reported. However, it was difficult to reproduce the issue predictably.

Please see comment to see the KCP resources (both old and new )
**Environment:**

- Cluster-api version: v0.3.7
- CAPBM version:v0.3.2
- Minikube version: v1.12.1
- environment (metal3-dev-env or other):
- Kubernetes version: (use `kubectl version`): v1.18.3

/kind bug

**Comment by Xenwar** [comment]
```
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  creationTimestamp: "2020-07-29T07:55:40Z"
    generation: 1
    labels:
      cluster.x-k8s.io/cluster-name: test1
    managedFields:
    - apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
      time: "2020-07-29T07:55:40Z"
    - apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
      time: "2020-07-29T07:55:52Z"
    name: test1
    namespace: metal3
    ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1alpha3
      kind: Cluster
      name: test1
      uid: de01ffaf-f60b-4b12-8769-c35ce805efcc
    resourceVersion: "5321"
    selfLink: /apis/controlplane.cluster.x-k8s.io/v1alpha3/namespaces/metal3/kubeadmcontrolplanes/test1
    uid: 1a4cfb62-b3d9-4ef4-9a16-3eb53ee437af
  spec:
    infrastructureTemplate:
    kubeadmConfigSpec:
      postKubeadmCommands:
      preKubeadmCommands:
    replicas: 1
    version: v1.18.0
ubuntu@upgrade-anwar-env:~/metal3-dev-env$ vim kcp-before-cleanup.yaml

# ----------------------------------------------------------------------------------------------------------------------------------
# New KCP After deprovision and provision
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  creationTimestamp: "2020-07-29T08:06:12Z"
  generation: 1
  managedFields:
  - apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    time: "2020-07-29T08:06:12Z"
  name: test1
  namespace: metal3
  resourceVersion: "7674"
  selfLink: /apis/controlplane.cluster.x-k8s.io/v1alpha3/namespaces/metal3/kubeadmcontrolplanes/test1
  uid: 13b5f898-a639-4aed-926c-b2647ed66138
spec:
  infrastructureTemplate:
  kubeadmConfigSpec:
    postKubeadmCommands:
    preKubeadmCommands:
  replicas: 1
  version: v1.18.0

```

**Comment by maelk** [comment]
did you leave sufficient time between the deprovisioning and the provisioning operations for the cluster objects to be deleted ? If not you would be somewhere between creating new objects and updating objects that have a deletion timestamp and will be deleted, anyways in an unstable scenario with unpredictable behaviour. you need to make sure all your resources were deleted before provisioning again

**Comment by Xenwar** [comment]
My view is a bit different.
I did not clean up properly on purpose. 
If the KCP is saved, the it should result in a CP node. That is what this issue is for.
And, the old and the new KCP should be handled separately.  

If, however, it is the setup in metal3-dev-env that has caused it, then we can close this issue.

**Comment by Xenwar** [comment]
To make my point a bit clearer,:
The source of truth is what is in the etcd and the controllers are to actuate that.
So, either we do not save it or the controllers have to act on it. 
My guess is that the saving event is lost or ignored.

**Comment by maelk** [comment]
Not really. the issue would rather be that your objects have the exact same name, so you are mainly updating an object that is undergoing deletion. and an update does not remove the deletion timestamp, so your KCP should end up deleted anyways, except if it had been deleted, and in that case you created a new one, but that needs to be for all objects, including the cluster object. Is it clearer ?

You can check the status of the objects after redproducing. Make sure you have all objects new. you probably won't have them. if you were to provision a totally different cluster (different name) then it should work fine. If not, you're risking not having the objects in the state you expect them if you don't give sufficient time for the deletion.

To put it bluntly, you should not provision again as long as you have pieces of the previous cluster still existing. Considering how CAPI and CAPM3, and K8S API, are designed, this can not work.

**Comment by Xenwar** [comment]
Ok. Thanks good to know.
