### ISSUE TITLE
Fix environment variable format for enableBMHNameBasedPreallocation

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/cluster-api-provider-metal3#1242]
**What steps did you take and what happened:**

We currently use the variable `enableBMHNameBasedPreallocation` [here](https://github.com/metal3-io/cluster-api-provider-metal3/blob/073bb1c41782587c7dd9c1624efd304a2cf8b190/config/manager/manager.yaml#L25C18-L25C49).
Unfortunately, clusterctl does not pick up variables using this format (lower case), as explained [here](https://github.com/kubernetes-sigs/cluster-api/pull/9513/files). We should change the variable to the proper format.

Unfortunately, this means a change for users. And users may already be using this variable from the `clusterctl.yaml` config file (where is works correctly in the current format). I'm not sure what to think about this. Does it require a minor version bump?

Edit: I think we have to change the variable, but the flag can stay the same. It would be best to do this in a minor release since it would be a breaking change for users setting the variable in `clusterctl.yaml`.

```diff
          args:
            - "--webhook-port=9443"
-            - "--enableBMHNameBasedPreallocation=${enableBMHNameBasedPreallocation:=false}"
+            - "--enableBMHNameBasedPreallocation=${ENABLE_BMH_NAME_BASED_PREALLOCATION:=false}"
```

**What did you expect to happen:**

The variable should be picked up by clusterctl when generating `infrastructure-components.yaml`. See https://github.com/kubernetes-sigs/cluster-api/issues/8097 for more details.

/kind bug

**Comment by Rozzii** [comment]
This is something that we would like to implement but currently no-one is working on this so I am moving it to frozen.
/lifecycle frozen
/help

**Comment by adilGhaffarDev** [comment]
this is fixed in https://github.com/metal3-io/cluster-api-provider-metal3/pull/1751
