### ISSUE TITLE
Implement the ClusterClass API

### ISSUE THREAD

**Issue by gomesrup** [metal3-io/cluster-api-provider-metal3#1267]
**User Story**

As an operator, I would like to be able to use the [ClusterClass](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20210526-cluster-class-and-managed-topologies.md) API for all the reasons listed in the [Motivations paragraph](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20210526-cluster-class-and-managed-topologies.md#motivation) of said proposal. 

**Detailed Description**

As I see it, the only missing part is the addition of a `Metal3ClusterTemplate` CRD, which embeds the `Metal3ClusterSpec` type. If I understand it correctly, no additional controller logic is required, as it is handled by the ClusterAPI itself :
- https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/controllers/topology/cluster/cluster_controller.go#L275
- https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/controllers/topology/cluster/desired_state.go#L57
- https://github.com/kubernetes-sigs/cluster-api/blob/main/internal/controllers/topology/cluster/desired_state.go#L160
- https://github.com/kubernetes-sigs/cluster-api/blob/main/controllers/external/util.go#L197

**Anything else you would like to add:**

It seems this is a quick-win feature, which was already asked for on the community Slack :
- https://kubernetes.slack.com/archives/CHD49TLE7/p1684166116481899
- https://kubernetes.slack.com/archives/CHD49TLE7/p1636058124100500

/kind feature

**Comment by Rozzii** [comment]
/triage accepted
/help
I would like to share it with you folks too @lentzi90 @kashifest , I think this was discussed multiple times.

**Comment by kashifest** [comment]
Yes, this was in my to do list, happy to take help if @gomesrup is eager to push it, otherwise I will work on it soon.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
I've added PR on this: #1405 
I still need to create testing environment so this was not tested, hence tagged it as draft for now.

**Comment by Rozzii** [comment]
thanls for the contribution @p-strusiewiczsurmacki-mobica I have ccd the relevant folks on the PR

**Comment by p-strusiewiczsurmacki-mobica** [comment]
I think the PR is ready for review. Please check [my comment there](https://github.com/metal3-io/cluster-api-provider-metal3/pull/1405#issuecomment-1927681112) for more info. :)
