### ISSUE TITLE
Need manually set boot from pxe when reinstall system

### ISSUE THREAD

**Issue by xinzhongyoumeng** [metal3-io/cluster-api-provider-metal3#1368]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

When I begin reinstall system,  I need manually set boot from pxe, so that can reinstall system. Otherwise，the server only reboot.
After reinstall system complete，reboot，it also boot from original system.
**What did you expect to happen:**

When reinstall system complete, reboot ,it can boot from new system.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Cluster-api-provider-metal3 version:
- Environment (metal3-dev-env or other):
- Kubernetes version: (use `kubectl version`):

/kind bug

**Comment by Rozzii** [comment]
At minimum we would need:
  - The environment section to be populated with the relevant environment info in the issue
  - We would need to know what BMC protocol were you using Redfish/IPMI etc
  - We would need to know what is the content of the ironic config file in the ironic container /etc/ironic/ironic.conf
  - Ironic logs would be also useful from the time period when the Ironic was unable to set the boot method correctly

**Comment by xinzhongyoumeng** [comment]
I see the log in ironic
```
install_bootloader: result "None", error "{'type': 'DeviceNotFound', 'code': 404, 'message': 'Error finding the disk or partition device to deploy the image onto', 'details': 'No partition with UUID 0xc65626fc found on device /dev/sda'}" get_commands_status /usr/lib/python3.9/site-packages/ironic/drivers/modules/agent_client.py:346
```
As a solution, I see the root device UUID by cli can set
```
 baremetal node set $NODE_UUID --instance-info image_rootfs_uuid=<uuid>
```
but I can not find how to set this in metal3

**Comment by Rozzii** [comment]
Do you still need help @xinzhongyoumeng
/remove-lifecycle stale
