### ISSUE TITLE
Issue with Cluster Creation in Metal3 Provider due to GitHub Download Failure

### ISSUE THREAD

**Issue by fracappa** [metal3-io/cluster-api-provider-metal3#1395]
Greetings,

I am currently in the process of utilizing Metal3 for provisioning my Kubernetes cluster on bare metal infrastructure. The hardware inspection phase with the bare metal operator was successful. However, I encountered an issue during the cluster creation phase while utilizing the cluster APIs.

I am following the instructions provided in the official guide [here](https://book.metal3.io/baremetal/guide#create-and-apply-cluster-controlplane-and-worker-template), but I am encountering the following error:

`Error: failed to read "cluster-template-development.yaml" from provider's repository "infrastructure-metal3": failed to download files from GitHub release v1.4.0: failed to get file "cluster-template-development.yaml" from "v1.4.0" release
`
This error is hindering the progress, and I would appreciate any assistance in resolving this issue.

**Additional Information**

-  Management Cluster Kubernetes version: 1.27.8
-  Target Cluster Kubernetes version: 1.29.0
- Metal3 Provider version: 1.4.0
- Followed instruction: [Baremetal provision](https://book.metal3.io/baremetal/guide)
- Management cluster: running on baremetal and set with kubeadm, not with minikube 

/kind bug

**Comment by tuminoid** [comment]
@lentzi90 has discussed with @fracappa in Slack about this: https://kubernetes.slack.com/archives/CHD49TLE7/p1705322273513209

**Comment by tuminoid** [comment]
(Not to discourage the discussion here, but friendly reminder that 1.4 release is EOL as of last week.)

**Comment by lentzi90** [comment]
Ref:
https://github.com/metal3-io/metal3-docs/blob/95aebb3468d68bb301664b8d9c55f44dd3001e5b/docs/user-guide/src/baremetal/guide.md?plain=1#L218

**Comment by adilGhaffarDev** [comment]
> @adilGhaffarDev do you remember where this came from? Should we add a development flavor?

I think its added by mistake, I will update the documentation and remove it.
