### ISSUE TITLE
[Flake] Upgrade test fails to clean up

### ISSUE THREAD

**Issue by huutomerkki** [metal3-io/cluster-api-provider-metal3#1453]
**Which jobs are flaking?**

job/metal3_daily_from-release-0-5_main_e2e_clusterctl_upgrade_test_ubuntu

**Which tests are flaking?**

job/metal3_daily_from-release-0-5_main_e2e_clusterctl_upgrade_test_ubuntu

**Since when has it been flaking?**

Build #292 (Feb 19, 2024, 1:05:00 AM)

**Jenkins link**

https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_from-release-0-5_main_e2e_clusterctl_upgrade_test_ubuntu/292/

**Reason for failure (if possible)**

Cleanup times out

**Comment by mboukhalfa** [comment]
failed again with the same issue before the `client_loop: send disconnect: Broken pipe`
https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_from-release-0-5_main_e2e_clusterctl_upgrade_test_ubuntu/295/consoleFull
https://jenkins.nordix.org/view/Metal3%20Periodic/job/metal3_daily_from-release-0-5_main_e2e_clusterctl_upgrade_test_ubuntu/293/consoleFull

All the other occurence failed before this step with `client_loop: send disconnect: Broken pipe `

**Comment by mboukhalfa** [comment]
/close 
we do not support release-0.5 anymore
