### ISSUE TITLE
Add pod and service CIDR variables in CAPM3 cluster-templates

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/cluster-api-provider-metal3#1484]
This issue is reserved for the KubeCon EU 2024 contrib-fest. Please do not work on it before 2024-03-20.

Service and Pod CIDR blocks in the [cluster-template](https://github.com/metal3-io/cluster-api-provider-metal3/blob/b207bcd07be1eb7ba4a504c197383f65ec86348c/examples/clusterctl-templates/clusterctl-cluster.yaml#L10-L13) should be overridable with variables in the same was as the CAPD [template](https://github.com/kubernetes-sigs/cluster-api/blob/93dc0cad6089748058ddd87ea509b9a233868a61/test/infrastructure/docker/templates/cluster-template-development.yaml#L9-L12).
Add variables and keep the default values the same as they are.

**Comment by rahulii** [comment]
@lentzi90 Thanks, I'd like to work on it.
What would be the good starting point to look at ?
