### ISSUE TITLE
Bump cert-manager

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/cluster-api-provider-metal3#1548]
Bump the cert-manager version. There has been many new releases of cert-manager since we last bumped the version.
No special actions och changes should be needed on our part for this. We just have to update the version to the latest.
It can be found in the following places:

- https://github.com/metal3-io/cluster-api-provider-metal3/blob/7dfb158db9fb6e503d38b40bb2253db1d8a5d8bc/test/e2e/config/e2e_conf.yaml#L136
- https://github.com/metal3-io/cluster-api-provider-metal3/blob/7dfb158db9fb6e503d38b40bb2253db1d8a5d8bc/examples/generate.sh#L118
- https://github.com/metal3-io/cluster-api-provider-metal3/blob/7dfb158db9fb6e503d38b40bb2253db1d8a5d8bc/Tiltfile#L18

**Comment by lekaf974** [comment]
@MeenuyD in the PR I used `v1.14.0` but `v1.14.4` is available should I use it instead ?

**Comment by tuminoid** [comment]
> @MeenuyD in the PR I used `v1.14.0` but `v1.14.4` is available should I use it instead ?

Use the latest patch available, please.

**Comment by lekaf974** [comment]
already mergeD, I will push another PR with latest patch number soon
