### ISSUE TITLE
CAPM3 v1.6.1 CAPI/CAPM3 machine name changed after rolling upgrade while nodeReuse set to True

### ISSUE THREAD

**Issue by jparkash2** [metal3-io/cluster-api-provider-metal3#1584]
**What steps did you take and what happened:**
Longhorn doesn't reuse old replicas after rolling upgrades and creates new replicas instead.

We conducted the rolling upgrade of CAPI with specific configurations, setting `nodeResue` to `true`, `automatedCleaningMode` to `disabled` at Metal3, and `replica-replenishment-wait-interval` set to `3600` on Longhorn. However, despite these settings, Longhorn did not utilize existing data. Instead, it created a new replica copy from the existing copy after the timeout of replica-replenishment-wait-interval even the node joined back the longhorn/kubernates cluster within the `replica-replenishment-wait-interval` time but with a new name. This behaviour was unexpected and not in line with our testing expectations.

After CAPI rolling upgrade, we have the below observations regarding Longhorn:

1. longhorn doesn't use old replica
2. It creates a new replica after the expiration of `replica-replenishment-wait-interval`
3. It is observed that during the provisioning of baremetal, CAPI machine/node name got changed. Due to this, longhorn consider it as a new node and doesn't use the existing longhorn replica.

Upon further investigation, we identified the root cause of the issue. It appears that during the rolling upgrade, the  CAPI machine name changed, resulting in Kubernetes/Longhorn cluster treating the updated node as a new node rather than the existing one.

**What did you expect to happen:**
After the rolling upgrade Kubernates cluster node name should not change to use existing data on disk to rebuild the replicas instead of create the new copy of replicas.
* Longhorn should not create new replica and should reuse existing (i.e. old) replica
* Longhorn should rebuild the data using existing (i.e. old) replica

**Anything else you would like to add:**
https://gitlab.com/sylva-projects/sylva-core/-/issues/1141

**Environment:**

- Cluster-api version: v1.6.3
- Cluster-api-provider-metal3 version: v1.6.1
- Environment (metal3-dev-env or other): management cluster on CAPO and workload cluster on Baremetal
- Kubernetes version: (use `kubectl version`): 1.27.10

/kind bug

**Comment by jparkash2** [comment]
@guettli Thanks, we can close this thread as it was achieved by making changes at CAMP3.

**Comment by guettli** [comment]
@jparkash2 how did you solve that? The issue at Longhorn is still open: https://github.com/longhorn/longhorn/issues/8362

**Comment by hardys** [comment]
We can cross-reference the related Sylva issues which I think contain some details around how this was resolved;

- https://gitlab.com/sylva-projects/sylva-core/-/issues/1141
- https://gitlab.com/sylva-projects/sylva-core/-/issues/1148

I think this is not a CAPM3 issue, but steps must be taken to ensure that cleaning is disabled and the Node name is reused which should perhaps be better documented somewhere

**Comment by guettli** [comment]
@hardys we use constant node names. Unfortunately I don't see how to solve the. 

The Longhorn node resource contains the config which you configure via the GUI. If cluster API upgrades the node, the Kubernetes node gets deleted, and the Longhorn node object gets deleted, too. Now the configuration like tags are lost.

We think about that: a controller syncs the Longhorn node config into a new CRD or a config map.

When the node gets created, we can provide this config via longhorn default config annotation, or via update the Longhorn node resource or we use the Longhorn Python client.

All this is doable. I am just confused that we seem to be the first to automate that. 

I like software development, but I am also happy if it's not needed :-)

---

How do you attach the data disk to Longhorn? Is a manual re-attach needed after capi upgraded the machine?
