### ISSUE TITLE
Prepare for release 1.7

### ISSUE THREAD

**Issue by kashifest** [metal3-io/cluster-api-provider-metal3#1595]
Here we can track the tasks related to release 1.7

- [x] Add/edit JJBs to acommodate new build jobs and PR jobs for new release branches
    - PR: https://gerrit.nordix.org/c/infra/cicd/+/20875
- [x] Add Prow jobs for new release branches in Project-infra repo
    - PR: https://github.com/metal3-io/project-infra/pull/697
- [x] Prepare dev-env to acommodate release-1.7 related changes and configurations
    - PR: https://github.com/metal3-io/metal3-dev-env/pull/1381
- [x] Update Metal3 book.
    - PR: https://github.com/metal3-io/metal3-docs/pull/413 
- [x] Release Ironic v24.1.1, also check new image is created in quay. 
    - PR: https://github.com/metal3-io/ironic-image/releases/tag/v24.1.1
- [x] Pin Ironic in BMO and release BMO v0.6.0, also check new image is created in quay. 
    - PR: https://github.com/metal3-io/baremetal-operator/pull/1679
- [x] Release IPAM v1.7.0 (Branch out, add branch protection and required tests, also check new image is created in quay) . 
- [x] Bump IPAM and BMO in CAPM3 
    - PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1605
- [x] Release CAPM3 v1.7.0 (Branch out, add branch protection and required tests, also check new image is created in quay).
    - CAPM3 v1.7.0: https://github.com/metal3-io/cluster-api-provider-metal3/releases/tag/v1.7.0
- [ ] Check CI if new releases are tested properly or not
- [x] Update CAPM3,IPAM and BMO README with the new e2e triggers
    - PR: https://github.com/metal3-io/cluster-api-provider-metal3/pull/1618
    - PR: https://github.com/metal3-io/ip-address-manager/pull/504
    - PR: https://github.com/metal3-io/baremetal-operator/pull/1694
- [x] Announce the releases

**Comment by tuminoid** [comment]
Ironic is 24.1.1

**Comment by kashifest** [comment]
> Ironic is 24.1.1

Corrected

**Comment by elfosardo** [comment]
ironic-image 24.1.1 has been released https://github.com/metal3-io/ironic-image/releases/tag/v24.1.1

**Comment by Sunnatillo** [comment]
Can we template this in somewhere in docs?

**Comment by mboukhalfa** [comment]
@kashifest @tuminoid @adilGhaffarDev Should be closed ?

**Comment by Rozzii** [comment]
@mboukhalfa  it should
/close
