### ISSUE TITLE
Prepare to CAPI v1alpha4

### ISSUE THREAD

**Issue by fmuyassarov** [metal3-io/cluster-api-provider-metal3#160]
Each CAPI infra providers are required to make some changes before taking CAPI v1alpha4 in.
CAPI community is working on the [document](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md) to list the changes required in provider side when moving from v1alpha3 to v1alpha4.

We can keep track of the work that needs to be done in CAPM3 in this issue.
/kind feature
/priority important-soon

**Comment by furkatgofurov7** [comment]
This can be closed since the CAPI uplift PR #167 got merged already.

/close
