### ISSUE TITLE
admission webhook "default.metal3machinetemplate.infrastructure.cluster.x-k8s.io" does not support dry run

### ISSUE THREAD

**Issue by levsha** [metal3-io/cluster-api-provider-metal3#166]
**What steps did you take and what happened:**

\# cat machine.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
kind: Metal3MachineTemplate
metadata:
  name: workers
  namespace: default
spec:
  template:
    spec:
      image:
        checksum: XXXXXXX
        checksumType: sha256
        format: null
        url: http://image.url/does.not.matter

\# kubectl -f machine.yaml apply --dry-run=server
Error from server (BadRequest): error when creating "machine.yaml": admission webhook "default.metal3machinetemplate.infrastructure.cluster.x-k8s.io" does not support dry run
\# kubectl -f machine.yaml diff
Error from server (BadRequest): admission webhook "default.metal3machinetemplate.infrastructure.cluster.x-k8s.io" does not support dry run

**What did you expect to happen:**

The manifest checked on the server side, kubectl shows the diff between the object definition on the cluster and in the file.

**Anything else you would like to add:**

According to the https://kubernetes.io/blog/2019/01/14/apiserver-dry-run-and-kubectl-diff/#how-to-enable-it to support server-side dry-run the mutating mutatingwebhook should not have any side effects when it processes dry-run requests and it should clearly mark this in the manifest using sideEffects field that should be set to None or NoneOnDryRun. The manifest does not set any value currently on https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/config/webhook/manifests.yaml . As it uses admissionregistration.k8s.io/v1beta1 version not setting any value of sideEffects means "Unknown", and "Requests with the dryRun attribute will be auto-rejected if they match a webhook with sideEffects == Unknown or Some." - https://kubernetes.io/docs/reference/kubernetes-api/extend-resources/mutating-webhook-configuration-v1/

**Environment:**

\# clusterctl upgrade plan
Checking cert-manager version...
Cert-Manager will be upgraded from "v0.11.0" to "v0.16.1"

Checking new release availability...

Management group: capi-system/cluster-api, latest release available for the v1alpha3 API Version of Cluster API (contract):

NAME                    NAMESPACE                           TYPE                     CURRENT VERSION   NEXT VERSION
bootstrap-kubeadm       capi-kubeadm-bootstrap-system       BootstrapProvider        v0.3.14           Already up to date
control-plane-kubeadm   capi-kubeadm-control-plane-system   ControlPlaneProvider     v0.3.14           Already up to date
cluster-api             capi-system                         CoreProvider             v0.3.14           Already up to date
infrastructure-metal3   capm3-system                        InfrastructureProvider   v0.4.1            Already up to date

You are already up to date!

\# minikube version
minikube version: v1.17.1
commit: 043bdca07e54ab6e4fc0457e3064048f34133d7e
\# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:14:17Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
\# kubectl get nodes
NAME                       STATUS   ROLES                  AGE   VERSION
clusterapi-control-plane   Ready    control-plane,master   26h   v1.20.2

/kind bug

**Comment by maelk** [comment]
I think this was fixed in the  linked PR
/close
