### ISSUE TITLE
Add OutOfServiceTaint to Node Instead of Deleting Node Object

### ISSUE THREAD

**Issue by clobrano** [metal3-io/cluster-api-provider-metal3#1725]
**User Story**

As an operator, I would like to add an `OutOfServiceTaint` to a Node instead of deleting the Node
object.

- use core functionality to obtain the same goal is a cleaner approach
- no need to backup and restore the Node

**Detailed Description**

For Kubernetes >= 1.28
Add the out-of-service taint in place of deleting the Node object Kubernetes >= 1.28

For Kubernetes < 1.28
Keep the current behavior 

**Anything else you would like to add:**

/kind feature

**Comment by clobrano** [comment]
I introduced this request on [slack](https://kubernetes.slack.com/archives/CHD49TLE7/p1715114774386869) and I'd like to implement it

**Comment by Rozzii** [comment]
Previous proposal: https://github.com/metal3-io/cluster-api-provider-metal3/pull/367
K8s feature related info: https://kubernetes.io/blog/2023/08/16/kubernetes-1-28-non-graceful-node-shutdown-ga/
I am okay with this:
/triage accepted

**Comment by clobrano** [comment]
Great, working on it
