### ISSUE TITLE
Bump CAPM3 1.6 release branch to Golang 1.22

### ISSUE THREAD

**Issue by tuminoid** [metal3-io/cluster-api-provider-metal3#1829]
Release branch release-1.6 has Golang 1.21.x in use. Golang 1.21 support ends in August 2024, when Golang 1.23 is released.

CAPM3 1.6 is in support for some time still, so we need to bump it to Go 1.22 before next patch release.

**Comment by Rozzii** [comment]
The GO version has been uplifted, thanks for all the contributors!
