### ISSUE TITLE
Add baremetal node deprovisioning confirm

### ISSUE THREAD

**Issue by shibaPuppy** [metal3-io/cluster-api-provider-metal3#1849]
**User Story**

As a [developer/user/operator] I would like to [high level description] for [reasons]
If an operator accidentally reduces the replicas of a machine deployment, many nodes will be deprovisioned at once.

**Detailed Description**

[A clear and concise description of what you want to happen.]
CAPM3 is a special controller because it controls baremetal nodes.
If the machine is deleted due to a user's mistake, CAPM3 modifies the resources of the bmh and deprovisions the baremetal node.
At this time, it would be good to have a branch that checks whether to remove the dperovisioning image field by checking the value of bmh metadata.label.remove=true by checking an environment variable such as CAPM3_AUTO_REMOVE=true.

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by Rozzii** [comment]
Have you tried to use finalizers to block machine deletion? But in any case could you please explain in more detail what do you mean by this:
"At this time, it would be good to have a branch that checks whether to remove the dperovisioning image field by checking the value of bmh metadata.label.remove=true by checking an environment variable such as CAPM3_AUTO_REMOVE=true."

**Comment by dtantsur** [comment]
Also note: if you allow a BMH instance to get orphaned, how do you recover from this situation? Especially for users that do not have access to BMH CR's?

**Comment by Rozzii** [comment]
@shibaPuppy FYI this Issue is now steal, please provide the requested information otherwise the issue will be deleted.
