### ISSUE TITLE
Wrong order of actions when associating the BMH to the host

### ISSUE THREAD

**Issue by maelk** [metal3-io/cluster-api-provider-metal3#19]
**What steps did you take and what happened:**
Currently, some actions are taken to update the BMH dependencies object (BMC secret for example) to add a cluster label. Those step update the object before we update the BMH itself, meaning that if the BMH update fails, and the association reruns, we might end up with another BMH, but the secret of the first BMH will still have the label of the cluster for example.

**What did you expect to happen:**
The first thing done should be to associate the BMH. Then update its dependencies. Once all this is done, update the Metal3Machine

**Anything else you would like to add:**
This is for both v1a3 and v1a4

**Environment:**

- Cluster-api version: v1a3
- CAPBM version: v1a3 and v1a4
- Minikube version: NA
- environment (metal3-dev-env or other): NA
- Kubernetes version: (use `kubectl version`): NA

/kind bug

**Comment by kashifest** [comment]
@maelk I found only BMC Secret being updated before the host itself, is there any other dependent object?
