### ISSUE TITLE
Remove dependency CAPM3RELEASE variable from metal3-dev-env

### ISSUE THREAD

**Issue by adilGhaffarDev** [metal3-io/cluster-api-provider-metal3#2181]
**What steps did you take and what happened:**
When doing minor releases it's impossible to test the following PRs:

- https://github.com/metal3-io/metal3-dev-env/pull/1485/files
- https://github.com/metal3-io/cluster-api-provider-metal3/pull/2164/files

We always have to merge one without running any tests. The reason is `CAPM3RELEASE` variable, we set this variable in `metal3-dev-env` but configs for this variable are in `CAPM3`. 

**What did you expect to happen:**
These PRs should not be dependent on each other and we should be able to run the tests.

**Possible fix:**
Set the value of `CAPM3RELEASE` in `CAPM3` `ci-e2e.sh` script and `metal3-dev-env` should set the value only when there no default value coming from `CAPM3`.

/kind improvement

**Comment by tuminoid** [comment]
/triage accepted

This was hit, once again, after 1.9 minor was cut.
