### ISSUE TITLE
Metal3Data and IPAddressClaim objects have unpredictable names

### ISSUE THREAD

**Issue by schrej** [metal3-io/cluster-api-provider-metal3#244]
**What steps did you take and what happened:**
When creating a machine deployment, the Machines, Metal3Machines and Metal3DataClaims use names with a random suffix. When the Metal3DataClaims are fulfilled, those Metal3Data objects aren't using the same randomized names, but incremental ones instead. The IPAddressClaims that get created while creating Metal3Data objects also use those incremental names.

**What did you expect to happen:**
The Metal3Data and IPAddressClaim objects should use the same names as the the Metal3Machine they belong to. This makes it much easier to determine to which machine they belong to, and is also more in line with the behavior of Kubernetes.

**Anything else you would like to add:**
We noticed this issue while developing and testing a custom controller based on ip-address-manager to interface with our internal IPAM.

When deleting a Machine (e.g. to redeploy it), everything that belongs to the Machine gets deleted, including the Metal3Data and IPAddressClaim objects. CAPI then immediately creates a new Machine to keep the desired count of Machines. This leads to a new Metal3Data and IPAddressClaim to get created. But, since they use an incremental name, they are almost identical to the previous ones.

**Environment:**
- Cluster-api version: 0.3.20
- Cluster-api-provider-metal3 version: 0.4.2

/kind bug
cc @MaxRink

**Comment by maelk** [comment]
We are using incremental names for the Metal3Data to ensure that the index of the Metal3Data is unique. This way, two metal3Data cannot be created with the same index, Kubernetes would refuse it. The ipclaim then uses the same name as the metal3Data.
Changing this behavior would make it complicated to ensure that the index (or ip address for the ipaddress object) remains unique. We considered alternatives, but did not see one without race conditions.
