### ISSUE TITLE
kubectl delete cluster doesnt trigger correct cleanup of metal3 resources

### ISSUE THREAD

**Issue by MaxRink** [metal3-io/cluster-api-provider-metal3#264]
**What steps did you take and what happened:**
I have a cluster that is still provisioning and am trying to delete it by deleting the cluster object.
CAPI contract dictates that CAPM3 should then also start deleting its resources.
But that isnt happening, instead i end up with a stuck cluster, where i manually need to delete all resources with 
`delete cluster,metal3cluster,machine,metal3machine,metal3data,kcp,md,metal3datatemplate,ipaddress,ipclaim,metal3dataclaim,metal3machinetemplates,machinesets --all`
to actually get rid of the cluster.
**What did you expect to happen:**

Cleanup actually happens
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:0.3.2x
- Cluster-api-provider-metal3 version:0.4.2
- Environment (metal3-dev-env or other): other, prd
- Kubernetes version: (use `kubectl version`): not relevant

/kind bug

**Comment by fmuyassarov** [comment]
@MaXinjian 
I don't think that it is possible to have those objects created before `Cluster/Metal3Cluster` is `Provisioned`.
And technically, if you delete the `Custer` which is still `Provisioning`, CAPM3 still should able to delete the `Metal3Cluster`.

**Comment by fmuyassarov** [comment]
```
$ kubectl get cluster -A
NAMESPACE   NAME    AGE   PHASE
metal3      test1   74s   Provisioning

$ kubectl get m3cluster -A
NAMESPACE   NAME    AGE   READY   ERROR   CLUSTER   ENDPOINT
metal3      test1   77s                   test1     {"host":"192.168.111.249","port":6443}

$ kubectl delete cluster -n metal3 test1
cluster.cluster.x-k8s.io "test1" deleted

$ kubectl get m3cluster -A
No resources found
```

**Comment by MaXinjian** [comment]
> @MaXinjian
Thanks but seems you @ me for wrong, should be @MaxRink 
> I don't think that it is possible to have those objects created before `Cluster/Metal3Cluster` is `Provisioned`.
> And technically, if you delete the `Custer` which is still `Provisioning`, CAPM3 still should able to delete the `Metal3Cluster`.

**Comment by fmuyassarov** [comment]
> > @MaXinjian
> > Thanks but seems you @ me for wrong, should be @MaxRink
> > I don't think that it is possible to have those objects created before `Cluster/Metal3Cluster` is `Provisioned`.
> > And technically, if you delete the `Custer` which is still `Provisioning`, CAPM3 still should able to delete the `Metal3Cluster`.

Ops, sorry

**Comment by MaxRink** [comment]
Not reliably, no.

**Comment by furkatgofurov7** [comment]
/remove-lifecycle stale
@MaxRink please feel free to reopen or open the new issue if you encounter the same problem again in the future.

/close
