### ISSUE TITLE
CAPM3 references old BMH spec missing network-data

### ISSUE THREAD

**Issue by Lukasz-SendGrid** [metal3-io/cluster-api-provider-metal3#3]
**What steps did you take and what happened:**
The BMO referenced in go.mod `github.com/metal3-io/baremetal-operator v0.0.0-20200225121200-8161ce57c5af` references an old BMH spec which is missing network-data, merged in here: https://github.com/metal3-io/baremetal-operator/pull/348

When you then go to provision a cluster, CAPM3 will edit the BMH object and not keep the network-data originally defined in the BMH object as it's pointing at an older spec which does not contain it.

**What did you expect to happen:**
The network-data defined in the BMH CR does not get wiped during cluster creation, and persists through cluster creation.

**Anything else you would like to add:**
Keep up the great work on this awesome project :)

**Environment:**

- Cluster-api version:
- CAPBM version: current
- Minikube version: N/A
- environment (metal3-dev-env or other):
- Kubernetes version: (use `kubectl version`): v1.17.3

/kind bug

**Comment by maelk** [comment]
Thank you for reporting, We'll fix it asap!
