### ISSUE TITLE
reconcile.Delete() error return might result in objects not being deleted

### ISSUE THREAD

**Issue by kashifest** [metal3-io/cluster-api-provider-metal3#35]
Currently reconcile.Delete() returns error in cases for example, when the bareMetalMachine cannot be updated or when the associated userDataSecret cannot be deleted properly. This might result in cases where the deletion workflow beyond the error return leave objects not being deleted eventually. Ideally the errors should be accumulated and returned at the end allowing other objects to be deleted even if there are some error in the early stages of deletion workflow.

**Comment by maelk** [comment]
I don't think this is the case anymore @kashifest  ?

**Comment by kashifest** [comment]
I guess this was solved in one of your recent fixes? I don't recall which one

**Comment by maelk** [comment]
It was fixed here I think : https://github.com/metal3-io/cluster-api-provider-metal3/commit/319d9d51c8e2875e4c89849b3008b082bf039620
/close
