### ISSUE TITLE
Label Machine based on Host

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/cluster-api-provider-metal3#37]
One of the reasons for supporting the machine API is that we want metal3 clusters to work like other clusters. That means being able to identify machines based on their characteristics, without knowing to look at the host resource. We should therefore have a way to copy label information from hosts onto machines when the host is provisioned.

One way do that is by merging the labels on the host resource with the labels on the machine resource after the host is fully provisioned (some labels will be added when hardware is discovered).

We should decide whether to propagate the same labels up to the node. That would be especially useful for labels that provide information like where a host is located.

**Comment by maelk** [comment]
This could now be achieved by using the metadata feature to set labels through the Kubelet config done by kubeadm (https://github.com/metal3-io/metal3-docs/pull/85) , if the label keys are known beforehand. Does this fulfill this issue @dhellmann ?

**Comment by dhellmann** [comment]
> This could now be achieved by using the metadata feature to set labels through the Kubelet config done by kubeadm ([metal3-io/metal3-docs#85](https://github.com/metal3-io/metal3-docs/pull/85)) , if the label keys are known beforehand. Does this fulfill this issue @dhellmann ?

I had thought we would just have the cluster-api-provider copy labels off of the host onto the machine, but maybe that's not needed.

I will go ahead and close this ticket for now and we can reopen it or create a new one when the requirements are clearer.
