### ISSUE TITLE
Provide a solution for control-plane load-balancing

### ISSUE THREAD

**Issue by maelk** [metal3-io/cluster-api-provider-metal3#38]
This issue is related to https://github.com/metal3-io/cluster-api-provider-baremetal/issues/101. When provisioning a cluster, we need to set up a load-balancer for the control-plane, since we may not be able to rely on a cloud-provider load-balancer. With this issue, we will go through the different alternatives to set up an HA cluster on baremetal nodes without external load-balancer.

We will start with a design document opened to discussion.

**Comment by ileixe** [comment]
This is one of the missing parts to migrate our manual cluster to use cluster-api. I saw there is a way to use VIP using keepalived, but we need proper loadbalancing. (We've used kube-vip for this).

> Here is a first draft document with the scope and goals [WIP] : https://docs.google.com/document/d/1LLywou05ak7df1VYQns27k70s6NgA8I-fILuJPDJZfI

This doc mentioned BGP based loadbalancing that I want. Is there any progress for the approach?
