### ISSUE TITLE
Add field selector support to hostSelector

### ISSUE THREAD

**Issue by russellb** [metal3-io/cluster-api-provider-metal3#39]
PR metal3-io/cluster-api-provider-baremetal#74 added the `hostSelector` field to the baremetal Machine provider spec.  (See doc/api.md)

The initial `hostSelector` support includes the ability to specify `BareMetalHost` matching criteria based on matching labels.  It would also be interesting to add the option of specifying field selectors, so we can match on more than just labels.

A simple use case would be to match on `metadata.name` if you wanted to specify a specific `BareMetalHost` by name.  A workaround for this use case would be to add a unique label to each host.

Perhaps there are more interesting use cases around matching on hardware inventory details that are in the `BareMetalHost` status.

**Comment by maelk** [comment]
This is at least partially addressed by the Hardware classifier, closing for now, feel free to re-open if needed
/close
