### ISSUE TITLE
The Metal3ClusterToMetal3Machines function returns a machine

### ISSUE THREAD

**Issue by maelk** [metal3-io/cluster-api-provider-metal3#40]
**What steps did you take and what happened:**
The Metal3ClusterToMetal3Machines returns references to a machine, instead of a metal3machine. This is a remaining bit from v1alpha1.

**What did you expect to happen:**
It should return a reference to a Metal3Machine, hence m.Spec.InfrastructureRef.Name if set.

/kind bug

**Comment by kashifest** [comment]
I will look into it. 
/assign @kashif

**Comment by kashifest** [comment]
I will look into it
/assign @kashifest
