### ISSUE TITLE
UpdateObject function should operate on a deepcopy of the object

### ISSUE THREAD

**Issue by maelk** [metal3-io/cluster-api-provider-metal3#46]
**What steps did you take and what happened:**
the UpdateObject (and maybe createObject too) functions in metal3machine_manager.go (branch release-0.3) should operate on deepcopies of the object. Using the object directly translates into a lost status.

- Cluster-api version: 0.3.2
- CAPBM version: 0.3.0

/kind bug

**Comment by maelk** [comment]
This should be fixed both in master and in branch release-0.3

**Comment by Jaakko-Os** [comment]
How was the 'lost status' detected?
Is there a test case that reproduces this problem?

**Comment by maelk** [comment]
it was detected in the metadata implementation phase. There is no test case that tests this, but you could add one on the updateObject function. Calling the function with an object with the status , after the call the object should retain its status.
