### ISSUE TITLE
Live ISO support is missing in the v1beta1 and v1alpha5 API types

### ISSUE THREAD

**Issue by fmuyassarov** [metal3-io/cluster-api-provider-metal3#500]
Live ISO support was added to v1alpha3 and v1alpha4 API types in https://github.com/metal3-io/cluster-api-provider-metal3/commit/43d0ece54e7f839cf65821cb6e1e4d108b4a6b7a. However, we are currently missing it in v1alpha5, and v1beta1 API types https://github.com/metal3-io/cluster-api-provider-metal3/blob/a8098b4bc8d85db91de2a7456acc234e72f653c7/api/v1beta1/common_types.go#L71

/kind bug

**Comment by macaptain** [comment]
@dtantsur, we talked about a CI test on the mailing list covering this behavior. I made some progress in this area, but unfortunately haven't quite got time to finish. Luckily I've handed over the task of adding CI for 'live-is' to @Xenwar.

/assign @Xenwar
