### ISSUE TITLE
get BMH UID from metal3Machine resource in SetNodeProviderID

### ISSUE THREAD

**Issue by Xenwar** [metal3-io/cluster-api-provider-metal3#590]
The bmhID passed by the caller to SetNodeProviderID is not reliable and should be used for two reasons.
It is not new information, It was extracted from the providerID (also sent by the caller).

The providerID is retrieved from a metal3Machine resource
https://github.com/metal3-io/cluster-api-provider-metal3/blob/1464a1693312b669e16aa78c13ab05190aa9c984/baremetal/metal3machine_manager.go#L1320

The source of truth for the bmhID should be the current metal3Machine (m). 

To Do:
create a function that gets a list of bmh resources and filters based on the owner reference. 
It should return a single bmh resource. Then assign the ID to bmhID

Note:
Do not change the signature of SetNodeProviderID as doing so would required changing a lot of tests.
That can be done in test improvements in other PRs.

**Comment by Xenwar** [comment]
ProviderID logic has changed recently. Due to that, the suggested improvements are no longer relevant. closing this and the sub-issues.

**Comment by Xenwar** [comment]
The issue has surfaced again. Re-opening the issue again. Just to emphasise the main point, 
The `bmhID` is extracted from `Metal3Machine.Spec.ProviderID` that, in turn, comes from a user supplied templated. 
If the use supplies wrong value, the the bmhID is incorrect as well. 

Basically, the Metal3Machine, via owner reference, knows what bmh it is related to. And, using that reference, I can easily get the bmhID.

**Comment by furkatgofurov7** [comment]
/remove-lifecycle stale

This is still relevant. @lentzi90 by any chance you were planning to work on this?

**Comment by lentzi90** [comment]
Yes I can take it!
/assign

**Comment by adilGhaffarDev** [comment]
assigning this to myself @lentzi90 is busy with other tasks.
/assign

**Comment by furkatgofurov7** [comment]
/reopen

https://github.com/metal3-io/cluster-api-provider-metal3/pull/868 was reverted
