### ISSUE TITLE
CAPM3 should not select a BMH that is paused

### ISSUE THREAD

**Issue by maelk** [metal3-io/cluster-api-provider-metal3#64]
**What steps did you take and what happened:**
Currently, when selecting a BMH, CAPM3 verifies that the BMH is available and in ready/available state. This is problematic because the BMH could be paused indefinitely, causing the machine deployment to fail on timeout from CAPI side.

**What did you expect to happen:**
CAPM3 should not consider BMH that have the pause annotation.

- Cluster-api version: v0.3.3
- CAPBM version: v0.3.0

/kind bug

**Comment by maelk** [comment]
This needs to be fixed in master and release-0.3 branch

**Comment by maelk** [comment]
The modifications should be done in this part of the code : https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/baremetal/metal3machine_manager.go#L729

**Comment by Jaakko-Os** [comment]
> This needs to be fixed in master and release-0.3 branch

I checked and seems that BMH pause only in master branch

**Comment by maelk** [comment]
the Pause field is on the BMO side, it is independent of CAPM3. This issue is valid for release-0.3

**Comment by maelk** [comment]
@Jaakko-Os Please backport your bug, and close this issue only when the backport is merged.

**Comment by Jaakko-Os** [comment]
Checked on the BMO side and it seems that pause is handled in the reconcile-loop https://github.com/metal3-io/baremetal-operator/blob/master/pkg/controller/baremetalhost/baremetalhost_controller.go#L193

**Comment by maelk** [comment]
yes, but CAPM3 should not select a BMH that is paused. that is the bug we are talking about

**Comment by Jaakko-Os** [comment]
Now this bug report is ready to be closed
