### ISSUE TITLE
Control plane provisioning doesn't complete

### ISSUE THREAD

**Issue by shachard** [metal3-io/cluster-api-provider-metal3#653]
Hi,

1) I installed a mgmt. cluster using kind and used clusterctl to deploy the metal3 provider:
     clusterctl init --infrastructure metal3
2) Then I installed the bare-metal operator (from source) and ran ironic on the host using tools/run_local_ironic.sh (with podman).
3) I added 2 baremetal hosts, they were successfully inspected by ironic and show as "available"
4) I generated a yaml for a test cluster with one control plane node and one worker node:
      clusterctl generate cluster capi-quickstart   --kubernetes-version v1.24.0   --control-plane-machine-count=1   --worker-machine-count=1   > capi-quickstart.yaml
    I used the example variables at: 
      https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/examples/clusterctl-templates/example_variables.rc
5) I applied the yaml and saw that all the objects were created. I saw that one of the baremetalhosts has an indication of consumer:
      NAME     STATE       CONSUMER                                        ONLINE   ERROR   AGE
      node-0   available                                                              true                        4h36m
      node-1   available   capi-quickstart-controlplane-827zc   true                        4h36m
6) The machine object went into "provisioning" state but none of the baremetal hosts state has changed:
      NAME                                               CLUSTER           NODENAME   PROVIDERID   PHASE          AGE       VERSION
      capi-quickstart-77465bcf68-tjgw8   capi-quickstart                                                Pending        4h26m   v1.24.0
      capi-quickstart-k84rk                       capi-quickstart                                                Provisioning  4h26m   v1.24.0
7) I looked at the machine object and saw it is waiting for "NodeRef":
 Status:
  Bootstrap Ready:  true
  Conditions:
    Last Transition Time:  2022-06-28T10:31:28Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2022-06-28T10:31:28Z
    Status:                True
    Type:                  BootstrapReady
    Last Transition Time:  2022-06-28T10:31:28Z
    Status:                True
    Type:                  InfrastructureReady
    Last Transition Time:  2022-06-28T10:31:28Z
    Reason:                WaitingForNodeRef
    Severity:              Info
    Status:                False
    Type:                  NodeHealthy
  Last Updated:            2022-06-28T10:31:28Z
  Observed Generation:     2
  Phase:                   Provisioning
 Events:                    <none>

8) The log of capm3-controller-manager says: "Could not find Node Ref on Machine object, will retry"

- Cluster-api version: 1.1.4
- Cluster-api-provider-metal3 version: latest from master
- Kubernetes version: (use `kubectl version`): 1.24

Thanks,
Shachar

**Comment by shachard** [comment]
Thanks for replying,

Do you mean the logs of the metal3 pods or of the baremetal servers?
Why do you suspect a communication issue with ironic?
Ironic has successfully inspected the nodes but didn't start the actual provisioning, and the bmh object didn't change its state from "available".

Shachar

**Comment by furkatgofurov7** [comment]
Hi,

Sorry for being late on this. Is the IMAGE_URL set to provision the host is correct and available?

**Comment by shachard** [comment]
Hi,
I eventually succeeded in provisioning the nodes, the issue was the network interfaces -
I couldn't find a way to configure which interfaces to use so I needed to disable all the other interfaces on my node (in the BIOS) and leave only those I wanted to use. Is there any any way to control this as part of the deployment variables?

**Comment by furkatgofurov7** [comment]
Well, we do also directly set interface names explicitly https://github.com/metal3-io/metal3-dev-env/blob/main/tests/roles/run_tests/templates/cluster-template-workers-kubeadm-config-ubuntu.yaml#L15, you just have to make sure which one you wanted to use

**Comment by shachard** [comment]
This is the provisioning interface, right? Is there a way to specify the mgmt. interface as well? 
BTW, do you support using the same interface but different VLANs for provisioning and mgmt.? Are there examples for this?
