### ISSUE TITLE
Although my username exists in the reviewer list I could add lgtm 

### ISSUE THREAD

**Issue by mboukhalfa** [metal3-io/cluster-api-provider-metal3#660]
**What steps did you take and what happened:**
I added /lgtm comment on the PR #658 and I got the bot answer : `@mboukhalfa: adding LGTM is restricted to approvers and reviewers in OWNERS files. `

**What did you expect to happen:**
PR get LGTM label

/kind bug

**Comment by furkatgofurov7** [comment]
@mboukhalfa this is correct, since you are not in the OWNERS list (not synced with main branch) in the release-0.5 branch, you were not able to label the PR.

**Comment by mboukhalfa** [comment]
Ah I did not notice that ! Would be great if we can automated syncing the OWNERS file or it may be different for each branch !

**Comment by furkatgofurov7** [comment]
> Ah I did not notice that ! Would be great if we can automated syncing the OWNERS file or it may be different for each branch?

ideally it should be same. Regardless, this issue can be closed and if needed automation of OWNERS can be discussed in a separate issue IMO.
