### ISSUE TITLE
V1.1.2 fails with Storage Errors

### ISSUE THREAD

**Issue by MaxRink** [metal3-io/cluster-api-provider-metal3#665]
**What steps did you take and what happened:**

We rolled out v1.1.2 and started to notice that new nodes do not roll out anymore.
We took a look at the logs and noticed that writes for CAPI machines and other things are failing, but they work again after downgrading to 1.1.1

```
E0707 18:53:53.762011       1 controller.go:317] controller/metal3machinetemplate "msg"="Reconciler error" "error"="failed to update metal3Machine: ship-lab-1-md-12-hkmwb: Operation cannot be fulfilled on metal3machines.infrastructure.cluster.x-k8s.io \"ship-lab-1-md-12-hkmwb\": StorageError: invalid object, Code: 4, Key: /registry/infrastructure.cluster.x-k8s.io/metal3machines/metal3-refaz-bn/ship-lab-1-md-12-hkmwb, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 910e5105-1d4f-4274-82ab-8be6ac47b409, UID in object meta: " "name"="ship-lab-1-md-12" "namespace"="metal3-refaz-bn" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="Metal3MachineTemplate" 

```
Full logs:
https://gist.github.com/MaxRink/6e0f56c8f3f00718ccc5e008a32060ba

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
```
NAME                     NAMESPACE                           TYPE                     CURRENT VERSION   NEXT VERSION
bootstrap-kubeadm        capi-kubeadm-bootstrap-system       BootstrapProvider        v1.1.5            Already up to date
control-plane-kubeadm    capi-kubeadm-control-plane-system   ControlPlaneProvider     v1.1.5            Already up to date
cluster-api              capi-system                         CoreProvider             v1.1.5            Already up to date
infrastructure-metal3    capm3-system                        InfrastructureProvider   v1.1.2            Already up to date
infrastructure-vsphere   capv-system                         InfrastructureProvider   v1.3.0            Already up to date
```
- Cluster-api-provider-metal3 version:
- Environment (metal3-dev-env or other):
- Kubernetes version: (use `kubectl version`):

/kind bug

**Comment by Xenwar** [comment]
In reference to our conversation on slack, 
A note on the absence of the providerID and presence of the node-label on the template. 
```
          node-labels: "metal3.io/uuid={{ '{{ ds.meta_data.uuid }}' }}"
          provider-id: "metal3://{{ '{{ ds.meta_data.uuid }}' }}"
```
The purpose of the `node-labels` is to **locate** the node/server and **assign** it the `provider-id`. 
So, if you omit the `provider-id` for any reason, then the `node-labels` should be omitted as well.

**Comment by MaxRink** [comment]
@Xenwar this is unrelated, thats the issue preventing us from trying if it still occours in the latest version

**Comment by furkatgofurov7** [comment]
@schrej is this by any chance related to https://github.com/metal3-io/cluster-api-provider-metal3/pull/693#issuecomment-1247952527?

**Comment by schrej** [comment]
No. #693 blocked us because we're directly setting image hashes, and the validation prevented us from doing so.

We tried to debug where these storage errors come from but weren't able to figure it out so far.

**Comment by Rozzii** [comment]
I have not heard about this issue since from any other source, is it still relevant to you @MaxRink ?

**Comment by MaxRink** [comment]
Were not observing that in current Versions. I guess it was a very
specific controller-runtime bug

Am Mi., 18. Jan. 2023 um 15:38 Uhr schrieb Adam Rozman
***@***.***>:

**Comment by furkatgofurov7** [comment]
/close

@MaxRink feel free to reopen it in the future in case it is still relevant.
