### ISSUE TITLE
failed to update BaremetalHost: host not found for machine

### ISSUE THREAD

**Issue by k82cn** [metal3-io/cluster-api-provider-metal3#682]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

Metal3Machine failed to update BareMetalHost, and there's no other log between Associate and Update as follow. It seems Associate return at https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/baremetal/metal3machine_manager.go#L297 , and can not recovered.

```
I0811 07:15:49.786114       1 metal3machine_manager.go:294] controllers/Metal3Machine/Metal3Machine-controller "msg"="Associating machine" "cluster"="dpu-cluster" "metal3-cluster"="dpu-cluster" "metal3-machine"={"Namespace":"default","Name":"dpu-cluster-controlplane-8h4dc"} "machine"="dpu-cluster-9vh7m"
I0811 07:15:49.786257       1 metal3machine_manager.go:733] controllers/Metal3Machine/Metal3Machine-controller "msg"="Updating machine" "cluster"="dpu-cluster" "machine"="dpu-cluster-9vh7m" "metal3-cluster"="dpu-cluster" "metal3-machine"={"Namespace":"default","Name":"dpu-cluster-controlplane-8h4dc"} 
E0811 07:15:49.787410       1 controller.go:317] controller/metal3machine "msg"="Reconciler error" "error"="failed to update BaremetalHost: host not found for machine dpu-cluster-9vh7m" "name"="dpu-cluster-controlplane-8h4dc" "namespace"="default" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="Metal3Machine" 
```

**What did you expect to happen:**

Associate Metal3Machine with BareMetalHost, and provision them.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: `clusterctl version: &version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.5", GitCommit:"d488bdb875d302eba85221fa35c9f13c00df4ae7", GitTreeState:"clean", BuildDate:"2022-07-04T13:59:55Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cluster-api-provider-metal3 version:
- Environment (metal3-dev-env or other): on-prem env
- Kubernetes version: (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.2-rc.0.33+050f930f896887", GitCommit:"050f930f8968874855eb215f0c0f0877bcdaa0e8", GitTreeState:"clean", BuildDate:"2022-06-15T11:38:02Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"archive", BuildDate:"2022-06-13T11:38:54Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

/kind bug

**Comment by k82cn** [comment]
That's because the configuration is incorrect, but when I correct that, it does not bind to BMH.

**Comment by schrej** [comment]
I just ran into the same problem with an incorrect configuration failing silently. There is no log message when the configuration is invalid (why?), but an error status is set on the Metal3Machine status. Unfortunately that error gets overwritten briefly after the `Associate` method finishes [here](https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/controllers/metal3machine_controller.go#L213).

**Comment by furkatgofurov7** [comment]
@k82cn hi. As I already [commented](https://github.com/metal3-io/cluster-api-provider-metal3/pull/683#issuecomment-1248489801) on the #683 can you confirm we are safe to close this?
