### ISSUE TITLE
Node.Spec.ProviderID not updated after Move

### ISSUE THREAD

**Issue by Arvinderpal** [metal3-io/cluster-api-provider-metal3#70]
After a clusterctl move from say a bootstrap cluster to a target cluster, the K.Node.Spec.ProviderID still contains the UID of the old BMH object. 

Simply updating the Node.Spec.ProviderID is not currently allowed as validation checks prevent Node.Spec.ProviderID to be changed after it has been set to a non-nil value (see https://github.com/kubernetes/kubernetes/pull/51761) 
	```Forbidden: node updates may not change providerID except from "" to valid, []: ```

Possible Solutions:
	1) Provide an option to have ProviderID be something other than UID of BMH -- for example: BMH 'Namespace/Name' may be unique for most environments. 
	2) Don’t use BMH.UID which is generated automatically during object creation but instead create a new field (say BMH.ProviderID) that we can populate with a random id. This field would be copied over as part of the move.
	3) Open an issue with K/K to allow updates to Node.Spec.ProviderID -- ie. Relax the validation checks.

/kind bug

xref: https://github.com/metal3-io/baremetal-operator/issues/431
@kashifest @maelk

**Comment by maelk** [comment]
Thanks, we'll take care of this in v1alpha4. I'd rather go with not using the UID, but another unique identifier such as namespace/name combination. We could also not tie it to the bmh anymore if it makes sense, especially considering the incoming metadata change that allow us a lot of flexibility

**Comment by maelk** [comment]
We could also keep it as is, considering that the provider id in our case is just used to match the machine and the node, and that it still appears in the machine correctly.

**Comment by Arvinderpal** [comment]
I'm fine with either Name+Namespace or a static ProviderID value that's not tied to UID.
The bug will manifest anytime someone tries to map K.Node <--> BMH.

**Comment by maelk** [comment]
Isn't it right now already a static ProviderID value ? It is created as the BMH UUID, but afterwards, for example if you do a move, then the only place you can find it is in the Metal3Machine Spec. So after a move you can still do the mapping with an intermediary step : K.Node <--> M3Machine <--> BMH if needed. If you take this approach from the start, whether we are using the original node UUID or a random UUID does not matter, does it ?

**Comment by Arvinderpal** [comment]
Yes, with the intermediary step things work out fine. However, for future reference, we should probably document that direct K.Node <---> BMH is not advisable b/c of the move operation.

**Comment by maelk** [comment]
Agreed with that. So we could solve this issue with a documentation update, right ?
