### ISSUE TITLE
Kubernetes version upgrade fails both new and old nodes due to keepalived failure

### ISSUE THREAD

**Issue by Xenwar** [metal3-io/cluster-api-provider-metal3#74]
**What steps did you take and what happened:**
In metal3-dev-env, set KUBERNETES_VERSION to "v1.18.0"

./scripts/v1alphaX/provision_cluster.sh 
./scripts/v1alphaX/provision_controlplane.sh 

Once provisioned, ssh into the node and run 
```kubeletcl get pods -A```, if you see pods, proceed. 

update k8s version to "v1.18.1" by edit the kcp resource. 
```kubectl edit kcp -n metal3```

After a while the upgrade process should start. 

However, both nodes are not usable for the following reason 
The new node (upgraded)
```
ubuntu@node-0:~$ kubectl get pods
The connection to the server 192.168.111.249:6443 was refused - did you specify the right host or port?
```

The original node
```
ubuntu@node-3:~$ kubectl get pods
The connection to the server 192.168.111.249:6443 was refused - did you specify the right host or port?
```

**What did you expect to happen:**
- A new nodes with kubernetes version v1.18.1 is provisioned.
- The existing node is deprovisioned.

**Anything else you would like to add:**

**Note: We should focus on why the original node has failed despite the new one not being successful.**

**Environment:**

- Cluster-api version: v1alpha3
- CAPM3 version: v1alpha3
- Minikube version: 1.9.2
- environment" metal3-dev-env
- Kubernetes version: v1.8.0 and v1.8.1

/kind bug

**Comment by maelk** [comment]
did you ssh on the nodes to check if one of them has the VIP assigned ? any keepalived logs ?

**Comment by Xenwar** [comment]
Original node
```
3: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:50:64:14:42:99 brd ff:ff:ff:ff:ff:ff
    inet 192.168.111.22/24 brd 192.168.111.255 scope global dynamic enp2s0
       valid_lft 2440sec preferred_lft 2440sec
    inet 192.168.111.249/32 scope global enp2s0
       valid_lft forever preferred_lft forever
    inet6 fe80::250:64ff:fe14:4299/64 scope link 
       valid_lft forever preferred_lft forever

```
And,
```
ubuntu@node-2:~$ kubectl get pods
The connection to the server 192.168.111.249:6443 was refused - did you specify the right host or port?

```

**Comment by Xenwar** [comment]
new node
```
3: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:50:64:14:42:91 brd ff:ff:ff:ff:ff:ff
    inet 192.168.111.20/24 brd 192.168.111.255 scope global dynamic enp2s0
       valid_lft 2862sec preferred_lft 2862sec
    inet6 fe80::250:64ff:fe14:4291/64 scope link 
       valid_lft forever preferred_lft forever

```
And, 
```
ubuntu@node-0:~$ kubectl get pods
The connection to the server 192.168.111.249:6443 was refused - did you specify the right host or port?

```

**Comment by Xenwar** [comment]
```
ubuntu@upgrade-env-anwar:~/logs$ kubectl get bmh -A
NAMESPACE   NAME     STATUS   PROVISIONING STATUS   CONSUMER                   BMC                         HARDWARE PROFILE   ONLINE   ERROR
metal3      node-0   OK       provisioned           test1-controlplane-4mzg2   ipmi://192.168.111.1:6230   unknown            true     
metal3      node-1   OK       ready                                            ipmi://192.168.111.1:6231   unknown            true     
metal3      node-2   OK       provisioned           test1-controlplane-lfdmb   ipmi://192.168.111.1:6232   unknown            true     
metal3      node-3   OK       ready                                            ipmi://192.168.111.1:6233   unknown            true     

```

**Comment by Xenwar** [comment]
```
capi-controller-manager-6b584cb4b7-v7nwq.log

I0430 05:48:01.281650       1 machine_controller_noderef.go:53] controllers/Machine "msg"="Machine doesn't have a valid ProviderID yet" "cluster"="test1" "machine"="test1-controlplane-fzjhg" "namespace"="metal3" 
E0430 05:48:01.281883       1 machine_controller.go:215] controllers/Machine "msg"="Reconciliation for Machine asked to requeue" "error"="Infrastructure provider for Machine \"test1-controlplane-fzjhg\" in namespace \"metal3\" is not ready, requeuing: requeue in 30s" "cluster"="test1" "machine"="test1-controlplane-fzjhg" "namespace"="metal3" 
I0430 05:48:04.055253       1 machine_controller_noderef.go:53] controllers/Machine "msg"="Machine doesn't have a valid ProviderID yet" "cluster"="test1" "machine"="test1-controlplane-fzjhg" "namespace"="metal3" 
....
E0430 05:48:41.909869       1 machine_controller.go:215] controllers/Machine "msg"="Reconciliation for Machine asked to requeue" "error"="cannot assign NodeRef to Machine \"test1-controlplane-fzjhg\" in namespace \"metal3\", no matching Node: requeue in 10s" "cluster"="test1" "machine"="test1-controlplane-fzjhg" "namespace"="metal3" 
E0430 05:52:12.948409       1 machine_controller_noderef.go:74] controllers/Machine "msg"="Failed to assign NodeRef" "error"="etcdserver: request timed out" "cluster"="test1" "machine"="test1-controlplane-fzjhg" "namespace"="metal3" 
E0430 05:52:12.950279       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="etcdserver: request timed out"  "controller"="machine" "request"={"Namespace":"metal3","Name":"test1-controlplane-fzjhg"}
I0430 05:52:13.077865       1 machine_controller_noderef.go:81] controllers/Machine "msg"="Set Machine's NodeRef" "cluster"="test1" "machine"="test1-controlplane-fzjhg" "namespace"="metal3" "noderef"="node-0"

```

**Comment by Xenwar** [comment]
capi-kubeadm-control-plane-controller-manager-57bcb55696-f9zk6.log

E0430 07:00:42.465143       1 controller.go:147] controllers/KubeadmControlPlane "msg"="Failed to update KubeadmControlPlane Status" "error"="failed to create remote cluster client: failed to create client for workload cluster metal3/test1: Get https://192.168.111.249:6443/api?timeout=30s: dial tcp 192.168.111.249:6443: connect: connection refused" "cluster"="test1" "kubeadmControlPlane"="test1-controlplane" "namespace"="metal3" 
E0430 07:00:42.466509       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="[failed to create client for workload cluster metal3/test1: Get https://192.168.111.249:6443/api?timeout=30s: dial tcp 192.168.111.249:6443: connect: connection refused, failed to create remote cluster client: failed to create client for workload cluster metal3/test1: Get https://192.168.111.249:6443/api?timeout=30s: dial tcp 192.168.111.249:6443: connect: connection refused]"  "controller"="kubeadmcontrolplane" "request"={"Namespace":"metal3","Name":"test1-controlplane"}
I0430 07:01:13.237270       1 controller.go:179] controllers/KubeadmControlPlane "msg"="Reconcile KubeadmControlPlane" "cluster"="test1" "kubeadmControlPlane"="test1-controlplane" "namespace"="metal3" 
I0430 07:01:13.238521       1 controller.go:225] controllers/KubeadmControlPlane "msg"="Upgrading Control Plane" "cluster"="test1" "kubeadmControlPlane"="test1-controlplane" "namespace"="metal3" 
E0430 07:01:13.242710       1 upgrade.go:43]  "msg"="failed to get remote client for workload cluster" "error"="failed to create client for workload cluster metal3/test1: Get https://192.168.111.249:6443/api?timeout=30s: dial tcp 192.168.111.249:6443: connect: connection refused" "cluster-name"="test1" "name"="test1-controlplane" "namespace"="metal3" "cluster key"={"Namespace":"metal3","Name":"test1"}
E0430 07:01:13.246184       1 controller.go:147] controllers/KubeadmControlPlane "msg"="Failed to update KubeadmControlPlane Status" "error"="failed to create remote cluster client: failed to create client for workload cluster metal3/test1: Get https://192.168.111.249:6443/api?timeout=30s: dial tcp 192.168.111.249:6443: connect: connection refused" "cluster"="test1" "kubeadmControlPlane"="test1-controlplane" "namespace"="metal3" 
E0430 07:01:13.247722       1 controller.go:258] controller-runtime/controller "msg"="Reconciler error" "error"="[failed to create client for workload cluster metal3/test1: Get https://192.168.111.249:6443/api?timeout=30s: dial tcp 192.168.111.249:6443: connect: connection refused, failed to create remote cluster client: failed to create client for workload cluster metal3/test1: Get https://192.168.111.249:6443/api?timeout=30s: dial tcp 192.168.111.249:6443: connect: connection refused]"  "controller"="kubeadmcontrolplane" "request"={"Namespace":"metal3","Name":"test1-controlplane"}

**Comment by Xenwar** [comment]
keepalived log, new node
```
Apr 30 05:52:14 node-0 Keepalived_vrrp[11007]: Opening file '/etc/keepalived/keepalived.conf'.
Apr 30 05:52:14 node-0 Keepalived_vrrp[11007]: Using LinkWatch kernel netlink reflector...
Apr 30 05:52:15 node-0 Keepalived_vrrp[11007]: VRRP_Instance(VI_2) Transition to MASTER STATE
Apr 30 05:52:15 node-0 Keepalived_vrrp[11007]: VRRP_Instance(VI_2) Received advert with higher priority 101, ours 101
Apr 30 05:52:15 node-0 Keepalived_vrrp[11007]: VRRP_Instance(VI_2) Entering BACKUP STATE

```
keepalived log, original node
```
Apr 30 05:39:57 node-2 Keepalived_vrrp[9132]: Opening file '/etc/keepalived/keepalived.conf'.
Apr 30 05:39:57 node-2 Keepalived_vrrp[9132]: Using LinkWatch kernel netlink reflector...
Apr 30 05:39:58 node-2 Keepalived_vrrp[9132]: VRRP_Instance(VI_2) Transition to MASTER STATE
Apr 30 05:39:59 node-2 Keepalived_vrrp[9132]: VRRP_Instance(VI_2) Entering MASTER STATE
Apr 30 05:52:15 node-2 Keepalived_vrrp[9132]: VRRP_Instance(VI_2) Received advert with lower priority 101, ours 101, forcing new election

```

**Comment by Xenwar** [comment]
> did you ssh on the nodes to check if one of them has the VIP assigned ? any keepalived logs ?

Relevant logs added. Also, issue description updated to point the focus of investigation.

**Comment by maelk** [comment]
>     inet 192.168.111.249/32 scope global enp2s0
The VIP is present on the old node, so it would look like keepalived is doing its job. The problem is probably somewhere else, no ?

**Comment by Xenwar** [comment]
I agree, this may not even be keepalived. However, as indicated on the description, this issue is a split of #42. 
I could be wrong, but I see two issues. 
1. The VIP should migrate to the new node
2. Until the new one succeeds, the old one should function as usual.

**Comment by maelk** [comment]
1. It depends, with the current configuration it would change to the new node only if the ip address is higher on the new node.
2. that's the core of the issue here. Is api-server still running ? did it crash ? any logs of errors on the node anywhere ?

**Comment by maelk** [comment]
And I would say that this issue is a metal3-dev-env issue, not a CAPM3, as it depends on the Kubeadmconfig templates that we provide in metal3-dev-env

**Comment by Xenwar** [comment]
>     1. It depends, with the current configuration it would change to the new node only if the ip address is higher on the new node.
> 
>     2. that's the core of the issue here. Is api-server still running ? did it crash ? any logs of errors on the node anywhere ?

Thanks. I will into both. And, move the issue to metal3-dev-env based on the outcome of the above two.

**Comment by Xenwar** [comment]
>     1. It depends, with the current configuration it would change to the new node only if the ip address is higher on the new node.
> 
>     2. that's the core of the issue here. Is api-server still running ? did it crash ? any logs of errors on the node anywhere ?

The issue is caused by 1. 
The VIP is kept in the old while there are not services running (etcd is one) on the old one. 
This issue can be closed.
