### ISSUE TITLE
Gosec complains when creating files with permission higher than 0600 and tests fail in the other case

### ISSUE THREAD

**Issue by mboukhalfa** [metal3-io/cluster-api-provider-metal3#763]
**What steps did you take and what happened:**
After moving `imageDownload` function to common.go `gosec` started complaining about creating file with permission higher than 0600 however if we created those files with 0600 permission the test will fail.

```
 [/home/prow/go/src/github.com/metal3-io/cluster-api-provider-metal3/test/e2e/common.go:106] - G306 (CWE-276): Expect WriteFile permissions to be 0600 or less (Confidence: HIGH, Severity: MEDIUM)
    105: 		md5sum := strings.Fields(string(output))[0]
  > 106: 		err = os.WriteFile(fmt.Sprintf("%s/%s.md5sum", ironicImageDir, rawImageName), []byte(md5sum), 0777)
    107: 		Expect(err).To(BeNil()) 

```
**What did you expect to happen:**
Changing permission for 0777 to 0600 and the tests pass

**Anything else you would like to add:**

**Environment:**

- Cluster-api version:
- Cluster-api-provider-metal3 version:
- Environment (metal3-dev-env or other):
- Kubernetes version: (use `kubectl version`):

/kind bug

**Comment by Rozzii** [comment]
This has been discussed offline and most probably this PR will be closed.
