### ISSUE TITLE
Default Metal3DataTemplate is missing in generated template files.

### ISSUE THREAD

**Issue by ileixe** [metal3-io/cluster-api-provider-metal3#820]
**What steps did you take and what happened:**

I tried to create cluster via `clusterctl generate cluster` and the m3m was not succeed as they could not find `Metal3DataTemplate`.

**What did you expect to happen:**

Machine should be created.

**Anything else you would like to add:**

https://kubernetes.slack.com/archives/CHD49TLE7/p1671776834225569

**Environment:**

- Cluster-api version: latest
- Cluster-api-provider-metal3 version: latest
- Environment (metal3-dev-env or other): Vanilla k8s 
- Kubernetes version: (use `kubectl version`): latest 

/kind bug

**Comment by lentzi90** [comment]
/triage accepted
We should at least document this, and I think it would also make sense to provide some kind of default. It will most likely be hard to create a template that works for everyone though. But with a template it should at least be more obvious what the problem is.
