### ISSUE TITLE
CAP3M doesn't start node provisioning after applying resources

### ISSUE THREAD

**Issue by criscola** [metal3-io/cluster-api-provider-metal3#889]
**What steps did you take and what happened:**

BMO + Ironic is deployed through the [deploy.sh script](https://github.com/metal3-io/baremetal-operator/blob/main/tools/deploy.sh) (`deploy.sh -b -i -t -m`), of course with some manual intervention to make it work. 

Kubernetes is deployed in the initial master node through the simplest kubeadm deployment.

Image I'm trying to provisiong with CAPI is Ubuntu 20.04 (`focal-server-cloudimg-amd64.img`).

CAPI manifests are generated through `clusterctl` by setting the relative environment variables as detailed in [getting-started.md](https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/docs/getting-started.md) and applied, but nothing happens.

Note that BMO marks node as `available` successfully (I also enabled SSH by editing the ramdisk image and checked for logs with journalctl but the provisioning command doesn't reach it). 

I placed the Ubuntu image on the preexisting HTTPD instance so it is accessible by the node to provision. Note that the node to provision doesn't have direct internet access.

Note also that I tried to provision the image through the BMO only (no CAPI layer) by setting the image field, and the operator marks the image as `provisioned` successfully.

According to the sequence diagram in [architecture.md](https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/docs/architecture.md#flow-of-information), the flow seems stuck at CAP3M having to set `userData` and `image` fields on the BMH, the rest went through.

**What did you expect to happen:**

I expected CAP3M to at least trigger the provisioning process, instead the image field is never applied to the BareMetalHost.
I also expected to find logs, errors or conditions that would point me in the direction of finding the issue but I could not find anything useful.

**Anything else you would like to add:**

Here's my BareMetalHost resource including status after applying the resources and waiting for it to get stuck:

https://pastebin.com/qQpEmHMH

Here's my manifests from clusterctl:

https://pastebin.com/qgtNvHBX

I couldn't find anything evident in the CAP3M controller logs but I can give any logs if you need.

Further logs:

All resources (`kubectl get all,secrets,configmaps -oyaml --all-namespaces`): https://pastebin.com/5mEtMqnC
logs of BMO: https://pastebin.com/t9HdJAH8
logs of CAPM3: https://pastebin.com/dv4z5P34
logs of IPAM: empty except for controller initialization logs
logs of CAPI: https://pastebin.com/tS6ttNYv

**Environment:**

- Cluster-api version: v1.3.3
- Cluster-api-provider-metal3 version: v1.3.0
- Environment (metal3-dev-env or other): Other
- Kubernetes version: (use `kubectl version`): v1.26.1

/kind bug

**Comment by lentzi90** [comment]
I think this may be a duplicate of https://github.com/metal3-io/cluster-api-provider-metal3/issues/820.
The issue has been fixed but is not yet included in a release. The cause is that the Metal3DataTemplate is missing. Adding this should allow the provisioning process to continue.

**Comment by lentzi90** [comment]
Update: Based on discussion on slack this is not a duplicate of #820 . Adding the Metal3DataTemplate did not help.

**Comment by Rozzii** [comment]
We have had a discussion on the community meeting with @criscola and @lentzi90  and @criscola  will provide reproduction steps.

**Comment by criscola** [comment]
Thanks for your kind support! I will add as much information as I can regarding reproduction steps. In the mean time I attached further logs to the issue as requested by @furkatgofurov7 over slack.

**Comment by lentzi90** [comment]
@criscola I think I found the cause!
In the manifests [linked on slack](https://pastebin.com/3Une8fn0) there is a Metal3DataTemplate for the control plane. But it has the wrong cluster name!

**Comment by criscola** [comment]
Yep, that was it, thank you so much! In the end it was a duplicate since metal3data wasn't configured correctly, https://github.com/metal3-io/cluster-api-provider-metal3/pull/821 will surely fix this kind of issues.
