### ISSUE TITLE
Add basic e2e test without clusterctl move

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/cluster-api-provider-metal3#897]
CAPI (and many other providers) have separate tests for `clusterctl move` and similar features, but the most basic tests just create a cluster and checks that it works. I think we should consider changing the "integration tests" to this basic form of just creating a cluster. We have plenty of other e2e tests that check `clusterctl move`.

Additionally, we should consider testing more configurations. The current tests focus on one configuration and runs all kinds of feature tests on it. We could run these basic tests on a wider variety, e.g. with or without IPAM, using ClusterClass or MachinePools, etc.

This would make CAPM3 similar to other providers and hopefully be less surprising for users. Maybe we can even shave off a few minutes on the integration tests?

/kind feature

**Comment by furkatgofurov7** [comment]
/triage accepted

Was wondering about the same when I was checking CAPI tests.
