### ISSUE TITLE
Enforcing Pod Security Standards For CAPM3

### ISSUE THREAD

**Issue by as20203** [metal3-io/cluster-api-provider-metal3#957]
I am currently working on adding a new feature of enforcing security standards for CAPI currently set to restricted level in the following PR
https://github.com/metal3-io/cluster-api-provider-metal3/pull/950

Regarding this PR, where should the security definitions go i.e. in some kustomization or directly applied from the manifest in the root?  Is there any specific way such file should be applied to the repository? Any other comments regarding this would also be appreciated.

**Comment by dtantsur** [comment]
Hi! This seems to be a question rather than a bug. To get help, please contact us on Slack: https://metal3.io/community-resources.html. You can also stop by our weekly meeting: https://groups.google.com/g/metal3-dev/c/sAsc9msfRZo.
