### ISSUE TITLE
"Failed to inspect hardware. Reason: unable to start inspection: HttpException: 401: Client Error for url

### ISSUE THREAD

**Issue by biu-hqh** [metal3-io/cluster-api-provider-metal3#989]
I deploy bmo，ironic and tls
![image](https://github.com/metal3-io/cluster-api-provider-metal3/assets/34858388/ba4e3b50-13df-4846-80b0-3afecb640421)

when I create bmh cr，I found bmh status stuck inspecting.This is the error log
oc logs -f baremetal-operator-controller-manager-54995d7b64-f96tp -n baremetal-operator-system -c manager

{"level":"info","ts":"2023-05-16T09:38:58Z","logger":"provisioner.ironic","msg":"current provision state","host":"metal3~node-27","lastError":"Failed to inspect hardware. Reason: unable to start inspection: HttpException: 401: Client Error for url: https://70.171.117.203:5050/v1/introspection/cb2ea234-b432-4f91-9b9a-cf0dcfe42e5a?manage_boot=False, the credentials required.: credentials (e.g., bad password), or your: requested.  Either you supplied the wrong: Unauthorized: 401 Unauthorized: are authorized to access the document: This server could not verify that you: browser doesn't understand how to supply","current":"inspect failed","target":"manageable"}

I went to curl at master node
![image](https://github.com/metal3-io/cluster-api-provider-metal3/assets/34858388/a6e8b706-80a7-4ce5-a176-5b1cf2f2fd07)

![image](https://github.com/metal3-io/cluster-api-provider-metal3/assets/34858388/0221349d-c2dd-49b5-a803-1daa03936083)

**Comment by Rozzii** [comment]
Please check what I have responded to your outher issue: https://github.com/metal3-io/baremetal-operator/issues/1274 let me know if it helps.

**Comment by Rozzii** [comment]
@biu-hqh do you need further assistance or can we close the ticket ?

**Comment by dtantsur** [comment]
Closing in favour of https://github.com/metal3-io/baremetal-operator/issues/1274
